import { expect, test, type Page } from '@playwright/test';
import { deflate } from 'pako';
import { gifFixture, heicFixture, tiffFixture } from '../fixtures/images';

const signature = Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
function crc32(data: Buffer): number { let crc=0xffffffff; for (const byte of data) { crc^=byte; for (let bit=0;bit<8;bit+=1) crc=(crc>>>1)^(0xedb88320&-(crc&1)); } return (crc^0xffffffff)>>>0; }
function pngChunk(type: string, data=Buffer.alloc(0)): Buffer { const name=Buffer.from(type); const length=Buffer.alloc(4); length.writeUInt32BE(data.length); const crc=Buffer.alloc(4); crc.writeUInt32BE(crc32(Buffer.concat([name,data]))); return Buffer.concat([length,name,data,crc]); }
function textChunk(type: 'tEXt'|'zTXt'|'iTXt', key: string, value: string): Buffer {
  if (type==='tEXt') return pngChunk(type,Buffer.concat([Buffer.from(key,'latin1'),Buffer.from([0]),Buffer.from(value,'latin1')]));
  if (type==='zTXt') return pngChunk(type,Buffer.concat([Buffer.from(key,'latin1'),Buffer.from([0,0]),Buffer.from(deflate(Buffer.from(value)))]));
  return pngChunk(type,Buffer.concat([Buffer.from(key,'latin1'),Buffer.from([0,0,0,0,0]),Buffer.from(value)]));
}
function png(texts: Array<['tEXt'|'zTXt'|'iTXt',string,string]> = []): Buffer {
  const ihdr=Buffer.alloc(13); ihdr.writeUInt32BE(2,0); ihdr.writeUInt32BE(1,4); ihdr.set([8,6,0,0,0],8);
  const scan=Buffer.from([0,239,106,56,255,217,255,67,255]);
  return Buffer.concat([signature,pngChunk('IHDR',ihdr),...texts.map((item)=>textChunk(...item)),pngChunk('IDAT',Buffer.from(deflate(scan))),pngChunk('IEND')]);
}

async function canvasImage(page: Page, mime: 'image/jpeg'|'image/webp'): Promise<Buffer> {
  const values=await page.evaluate(async(type)=>{ const canvas=document.createElement('canvas'); canvas.width=3; canvas.height=2; const context=canvas.getContext('2d')!; context.fillStyle='#ef6a38'; context.fillRect(0,0,3,2); const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob((value)=>value?resolve(value):reject(new Error('Canvas encoding failed')),type,.9)); return Array.from(new Uint8Array(await blob.arrayBuffer())); },mime);
  return Buffer.from(values);
}

function withExif(jpeg: Buffer): Buffer {
  const tiff=Buffer.alloc(700); tiff.write('II',0,'ascii'); tiff.writeUInt16LE(42,2); tiff.writeUInt32LE(8,4);
  const ifd0=8,exifIfd=98,gpsIfd=140; let cursor=194;
  const storeAscii=(value:string)=>{ const bytes=Buffer.from(`${value}\0`,'ascii'); const offset=cursor; bytes.copy(tiff,cursor); cursor+=bytes.length; return {offset,count:bytes.length}; };
  const storeRationals=(values:number[])=>{ const offset=cursor; for(const value of values){ tiff.writeUInt32LE(value,cursor); tiff.writeUInt32LE(1,cursor+4); cursor+=8; } return offset; };
  const entry=(offset:number,tag:number,type:number,count:number,value:number|string)=>{ tiff.writeUInt16LE(tag,offset); tiff.writeUInt16LE(type,offset+2); tiff.writeUInt32LE(count,offset+4); if(typeof value==='string') tiff.write(value,offset+8,'ascii'); else if(type===3&&count===1) tiff.writeUInt16LE(value,offset+8); else tiff.writeUInt32LE(value,offset+8); };
  const make=storeAscii('Pocket Camera'),model=storeAscii('DeskCam 42'),software=storeAscii('MetadataView Fixture'),artist=storeAscii('Ada Example');
  const date=storeAscii('2024:03:12 14:05:06'),serial=storeAscii('BODY-12345'),lens=storeAscii('35mm Test Lens'); const lat=storeRationals([37,46,30]),lon=storeRationals([122,25,10]);
  tiff.writeUInt16LE(7,ifd0); let e=ifd0+2;
  for(const spec of [[0x010f,2,make.count,make.offset],[0x0110,2,model.count,model.offset],[0x0112,3,1,6],[0x0131,2,software.count,software.offset],[0x013b,2,artist.count,artist.offset],[0x8769,4,1,exifIfd],[0x8825,4,1,gpsIfd]] as const){ entry(e,spec[0],spec[1],spec[2],spec[3]); e+=12; } tiff.writeUInt32LE(0,e);
  tiff.writeUInt16LE(3,exifIfd); e=exifIfd+2; for(const spec of [[0x9003,2,date.count,date.offset],[0xa431,2,serial.count,serial.offset],[0xa434,2,lens.count,lens.offset]] as const){ entry(e,spec[0],spec[1],spec[2],spec[3]); e+=12; } tiff.writeUInt32LE(0,e);
  tiff.writeUInt16LE(4,gpsIfd); e=gpsIfd+2; entry(e,1,2,2,'N\0'); entry(e+12,2,5,3,lat); entry(e+24,3,2,2,'W\0'); entry(e+36,4,5,3,lon); tiff.writeUInt32LE(0,e+48);
  const payload=Buffer.concat([Buffer.from('Exif\0\0','binary'),tiff.subarray(0,cursor)]); const length=Buffer.alloc(2); length.writeUInt16BE(payload.length+2);
  return Buffer.concat([jpeg.subarray(0,2),Buffer.from([0xff,0xe1]),length,payload,jpeg.subarray(2)]);
}

async function open(page: Page) { await page.goto('/image-metadata-viewer/'); await page.locator('astro-island:not([ssr])').waitFor({state:'attached'}); }
async function upload(page: Page,name:string,buffer:Buffer,mimeType:string){ await page.locator('input[type=file]').setInputFiles({name,buffer,mimeType}); }
async function ready(page: Page,name: string|RegExp=/metadata report$/){ await expect(page.getByRole('heading',{name})).toBeVisible({timeout:20_000}); }

test('ships the shared accessible evidence desk with all six image families',async({page})=>{ await open(page); await expect(page.getByRole('button',{name:'Choose an image'})).toBeVisible(); await expect(page.locator('input[type=file]')).toHaveAttribute('accept','.png,.jpg,.jpeg,.webp,.heic,.heif,.tif,.tiff,.gif,image/png,image/jpeg,image/webp,image/heic,image/heif,image/tiff,image/gif'); });
test('automatically runs one full image scan without staged controls',async({page})=>{ test.setTimeout(60_000); await open(page); await upload(page,'full-scan.png',png(),'image/png'); await ready(page); await expect(page.locator('.report-engine-copy strong')).toHaveText('Full scan complete',{timeout:30_000}); await expect(page.locator('.report-engine-stats')).toContainText(/ExifTool\s+\d/i); await expect(page.locator('.report-engine ol')).toHaveCount(0); await expect(page.getByRole('button',{name:/Scan embedded data|Retry standard scan/})).toHaveCount(0); });
test('reads a baseline PNG with dimensions, hashes, and its file header',async({page})=>{ await open(page); await upload(page,'pixel.png',png(),'image/png'); await ready(page,/pixel\.png metadata report/); await expect(page.getByText('2 × 1 px')).toBeVisible(); await expect(page.getByText('SHA-256 · primary fingerprint')).toBeVisible(); await expect(page.locator('.report-hashes code').first()).toHaveText(/^[a-f0-9]{64}$/); await expect(page.getByText(/File header · first \d+ bytes/)).toBeVisible(); });
test('reads PNG text and exposes friendly plus native source/path fields',async({page})=>{ await open(page); await upload(page,'author.png',png([['tEXt','Artist','Ada Example']]),'image/png'); await ready(page); await expect(page.getByText(/potentially sensitive field/)).toBeVisible(); await expect(page.locator('[data-field-path="png.text.Artist"]')).toContainText('Ada Example'); await page.getByRole('button',{name:/All native fields/}).click(); await expect(page.locator('.report-sections')).toContainText('Artist'); });
test('keeps compressed PNG parameters as native data without special interpretation',async({page})=>{ await open(page); await upload(page,'generated.png',png([['zTXt','parameters','orange cat\nSteps: 12, Seed: 42']]),'image/png'); await ready(page); await page.getByPlaceholder(/Search value/).fill('orange cat'); await expect(page.locator('.report-sections')).toContainText('orange cat'); await expect(page.getByText('AI generation data',{exact:true})).toHaveCount(0); await page.getByRole('button',{name:/All native fields/}).click(); await expect(page.locator('.report-sections')).toContainText('parameters'); });
test('keeps unknown UTF-8 iTXt fields searchable',async({page})=>{ await open(page); await upload(page,'unicode.png',png([['iTXt','odd-field','你好 from metadata']]),'image/png'); await ready(page); await page.getByPlaceholder(/Search value/).fill('你好'); await expect(page.locator('.report-sections')).toContainText('你好 from metadata'); });
test('reads real JPEG EXIF camera, date, serial, orientation, and GPS',async({page})=>{ await open(page); await upload(page,'camera.jpg',withExif(await canvasImage(page,'image/jpeg')),'image/jpeg'); await ready(page); await expect(page.locator('.report-sections')).toContainText('Pocket Camera'); await expect(page.locator('.report-sections')).toContainText('DeskCam 42'); await page.getByRole('button',{name:/All native fields/}).click(); await page.getByPlaceholder(/Search value/).fill('BODY-12345'); await expect(page.locator('.report-sections')).toContainText('BODY-12345'); await expect(page.getByRole('link',{name:'Open Privacy Checker'})).toBeVisible(); });
test('reads a browser-encoded WebP',async({page})=>{ await open(page); await upload(page,'pixel.webp',await canvasImage(page,'image/webp'),'image/webp'); await ready(page); await expect(page.getByText('WEBP',{exact:true}).first()).toBeVisible(); await expect(page.getByText('3 × 2 px')).toBeVisible(); });
test('reads HEIC spatial properties even when Chromium cannot preview the pixels',async({page})=>{ await open(page); await upload(page,'photo.heic',Buffer.from(heicFixture(640,480)),'image/heic'); await ready(page,/photo\.heic metadata report/); await expect(page.getByText('HEIC',{exact:true}).first()).toBeVisible(); await expect(page.locator('.report-facts')).toContainText(/640.*480 px/); });
test('reads TIFF image directories and falls back cleanly when preview decoding is unavailable',async({page})=>{ await open(page); await upload(page,'scan.tiff',Buffer.from(tiffFixture(320,240)),'image/tiff'); await ready(page,/scan\.tiff metadata report/); await expect(page.getByText('TIFF',{exact:true}).first()).toBeVisible(); await expect(page.locator('.report-facts')).toContainText(/320.*240 px/); await expect(page.locator('.report-sections')).toContainText(/little-endian/i); });
test('reads GIF comments and animation facts',async({page})=>{ await open(page); await upload(page,'loop.gif',Buffer.from(gifFixture({comment:'GIF contact sheet',animated:true})),'image/gif'); await ready(page,/loop\.gif metadata report/); await expect(page.getByText('GIF',{exact:true}).first()).toBeVisible(); await expect(page.locator('.report-sections')).toContainText('GIF contact sheet'); await expect(page.locator('[data-field-path="Animated"]')).toContainText(/Animated.*true/i); });
test('trusts the PNG signature over a misleading JPG extension and MIME',async({page})=>{ await open(page); await upload(page,'renamed.jpg',png(),'image/jpeg'); await ready(page); await expect(page.getByText('PNG',{exact:true}).first()).toBeVisible(); await expect(page.locator('.report-warnings')).toContainText(/filename suggests JPEG/i); await expect(page.locator('.report-warnings')).toContainText(/browser reported image\/jpeg/i); });
test('rejects unsupported bytes and recovers with a valid image',async({page})=>{ await open(page); await upload(page,'fake.png',Buffer.from('not really an image'),'image/png'); await expect(page.getByRole('alert')).toContainText(/file signature/i); await upload(page,'recovered.png',png(),'image/png'); await ready(page,/recovered\.png metadata report/); });
test('stops files over 50 MB before parsing',async({page})=>{ test.setTimeout(45_000); await open(page); await page.evaluate(()=>{ const file=new File([new Uint8Array(50*1024*1024+1)],'huge.png',{type:'image/png'}); const transfer=new DataTransfer(); transfer.items.add(file); document.querySelector('.report-dropzone')!.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer})); }); await expect(page.getByRole('alert')).toContainText('stops at 50 MB',{timeout:25_000}); });
test('handles multiple selection explicitly and opens only the first file',async({page})=>{ await open(page); await page.locator('input[type=file]').setInputFiles([{name:'first.png',buffer:png(),mimeType:'image/png'},{name:'second.png',buffer:png([['tEXt','Artist','Second']]),mimeType:'image/png'}]); await ready(page,/first\.png metadata report/); await expect(page.getByRole('status')).toContainText(/extra file was ignored/); await expect(page.getByText('second.png')).toHaveCount(0); });
test('search, source filter, view switch, and chapter navigation do not reparse',async({page})=>{ await open(page); await upload(page,'author.png',png([['tEXt','Artist','Ada Example']]),'image/png'); await ready(page); const hash=await page.locator('.report-hashes code').first().textContent(); await page.getByPlaceholder(/Search value/).fill('Ada Example'); await page.getByLabel('Filter by source').selectOption('PNG text'); await expect(page.locator('.report-sections')).toContainText('Ada Example'); await page.getByRole('button',{name:/All native fields/}).click(); await expect(page.locator('.report-chapters a').first()).toHaveAttribute('href',/^#/); expect(await page.locator('.report-hashes code').first().textContent()).toBe(hash); });
test('long values start shortened and expand on demand',async({page})=>{ await open(page); await upload(page,'long.png',png([['iTXt','Description','x'.repeat(12_000)]]),'image/png'); await ready(page); const expand=page.getByRole('button',{name:/Show all 12,000 characters/}).first(); await expect(expand).toBeVisible(); await expand.click(); await expect(page.getByRole('button',{name:'Show less'}).first()).toBeVisible(); });
test('raw JSON stays lazy until its panel opens',async({page})=>{ await open(page); await upload(page,'raw.png',png([['tEXt','Artist','Ada']]),'image/png'); await ready(page); await expect(page.locator('.report-raw-json')).toHaveText(''); await page.getByText('Raw safe JSON',{exact:true}).click(); await expect(page.locator('.report-raw-json')).toContainText('Artist'); });
test('copies one field, visible rows, and all rows',async({page,context})=>{ await context.grantPermissions(['clipboard-read','clipboard-write']); await open(page); await upload(page,'copy.png',png([['tEXt','Artist','Ada Example']]),'image/png'); await ready(page); await page.getByRole('button',{name:'Copy Artist'}).first().click(); await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toBe('Ada Example'); await page.getByRole('button',{name:'Copy visible'}).click(); await expect(page.getByRole('status')).toContainText(/visible fields copied/); await page.getByRole('button',{name:'Copy all'}).click(); await expect(page.getByRole('status')).toContainText(/fields copied/); });
test('downloads complete JSON, raw JSON, and a locally generated PDF',async({page})=>{ test.setTimeout(90_000); await open(page); await upload(page,'export.png',png([['tEXt','Artist','Ada']]),'image/png'); await ready(page); await expect(page.locator('.report-engine-copy strong')).toHaveText('Full scan complete',{timeout:30_000}); let event=page.waitForEvent('download'); await page.getByRole('button',{name:'Complete JSON'}).click(); expect((await event).suggestedFilename()).toMatch(/metadata-report\.json$/); event=page.waitForEvent('download'); await page.getByRole('button',{name:'Raw JSON'}).click(); expect((await event).suggestedFilename()).toMatch(/raw-metadata\.json$/); event=page.waitForEvent('download'); await page.getByRole('button',{name:'Readable PDF'}).click(); expect((await event).suggestedFilename()).toMatch(/metadata-report\.pdf$/); });
test('rapid replacement ignores stale results and shows the newest file',async({page})=>{ await open(page); const input=page.locator('input[type=file]'); await input.setInputFiles({name:'old.png',buffer:png([['iTXt','Description','x'.repeat(100_000)]]),mimeType:'image/png'}); await input.setInputFiles({name:'new.png',buffer:png([['tEXt','Artist','Newest']]),mimeType:'image/png'}); await ready(page,/new\.png metadata report/); await expect(page.getByText('old.png')).toHaveCount(0); });
test('keyboard activation, result focus, replace, and clear work',async({page})=>{ await open(page); const chooser=page.waitForEvent('filechooser'); await page.getByRole('button',{name:'Choose an image'}).press('Enter'); await (await chooser).setFiles({name:'keyboard.png',buffer:png(),mimeType:'image/png'}); const heading=page.getByRole('heading',{name:/keyboard\.png metadata report/}); await expect(heading).toBeVisible({timeout:20_000}); await expect(heading).toBeFocused(); const replacement=page.waitForEvent('filechooser'); await page.getByRole('button',{name:'Replace'}).click(); await (await replacement).setFiles({name:'replacement.png',buffer:png(),mimeType:'image/png'}); await ready(page,/replacement\.png metadata report/); await page.getByRole('button',{name:'Clear'}).click(); const choose=page.getByRole('button',{name:'Choose an image'}); await expect(choose).toBeVisible(); await expect(choose).toBeFocused(); });
test('selection sends no filename, hash input, or metadata values over the network',async({page})=>{ await open(page); const unsafe:string[]=[]; page.on('request',(request)=>{ if(request.method()!=='GET'||/secret-local-name|Private/.test(request.postData()??'')) unsafe.push(`${request.method()} ${request.url()}`); }); await upload(page,'secret-local-name.png',png([['tEXt','Artist','Private']]),'image/png'); await ready(page); expect(unsafe).toEqual([]); });
test('390px result has no page overflow and long values stay contained',async({page})=>{ await page.setViewportSize({width:390,height:844}); await open(page); await upload(page,'mobile.png',png([['iTXt','Description','x'.repeat(8_000)]]),'image/png'); await ready(page); const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth})); expect(width.scroll).toBeLessThanOrEqual(width.client+1); });
