import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { deflate } from 'pako';

const signature = Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
function crc32(data: Buffer): number { let crc=0xffffffff; for(const byte of data){crc^=byte;for(let bit=0;bit<8;bit+=1)crc=(crc>>>1)^(0xedb88320&-(crc&1));} return (crc^0xffffffff)>>>0; }
function chunk(type:string,data=Buffer.alloc(0)):Buffer { const name=Buffer.from(type);const length=Buffer.alloc(4);length.writeUInt32BE(data.length);const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(Buffer.concat([name,data])));return Buffer.concat([length,name,data,crc]); }
function png(texts:Array<[string,string]> = []):Buffer { const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(2,0);ihdr.writeUInt32BE(1,4);ihdr.set([8,6,0,0,0],8);const scan=Buffer.from([0,239,106,56,255,217,255,67,255]);return Buffer.concat([signature,chunk('IHDR',ihdr),...texts.map(([key,value])=>chunk('tEXt',Buffer.concat([Buffer.from(key,'latin1'),Buffer.from([0]),Buffer.from(value,'latin1')]))),chunk('IDAT',Buffer.from(deflate(scan))),chunk('IEND')]); }
function apng():Buffer { const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(2,0);ihdr.writeUInt32BE(1,4);ihdr.set([8,6,0,0,0],8);const animation=Buffer.alloc(8);animation.writeUInt32BE(1,0);const frame=Buffer.alloc(26);frame.writeUInt32BE(2,4);frame.writeUInt32BE(1,8);frame.writeUInt16BE(1,20);frame.writeUInt16BE(10,22);const scan=Buffer.from([0,239,106,56,255,217,255,67,255]);return Buffer.concat([signature,chunk('IHDR',ihdr),chunk('acTL',animation),chunk('fcTL',frame),chunk('IDAT',Buffer.from(deflate(scan))),chunk('IEND')]); }

async function canvasJpeg(page:Page):Promise<Buffer> { const values=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=3;canvas.height=2;const context=canvas.getContext('2d')!;context.fillStyle='#ef6a38';context.fillRect(0,0,3,2);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob((value)=>value?resolve(value):reject(new Error('JPEG fixture failed')),'image/jpeg',.9));return Array.from(new Uint8Array(await blob.arrayBuffer()));});return Buffer.from(values); }
function gpsJpeg(jpeg:Buffer):Buffer {
  const tiff=Buffer.alloc(700);tiff.write('II',0,'ascii');tiff.writeUInt16LE(42,2);tiff.writeUInt32LE(8,4);
  const ifd0=8,exifIfd=98,gpsIfd=140;let cursor=194;
  const ascii=(value:string)=>{const bytes=Buffer.from(`${value}\0`,'ascii');const offset=cursor;bytes.copy(tiff,cursor);cursor+=bytes.length;return{offset,count:bytes.length};};
  const rationals=(values:number[])=>{const offset=cursor;for(const value of values){tiff.writeUInt32LE(value,cursor);tiff.writeUInt32LE(1,cursor+4);cursor+=8;}return offset;};
  const entry=(offset:number,tag:number,type:number,count:number,value:number|string)=>{tiff.writeUInt16LE(tag,offset);tiff.writeUInt16LE(type,offset+2);tiff.writeUInt32LE(count,offset+4);if(typeof value==='string')tiff.write(value,offset+8,'ascii');else if(type===3&&count===1)tiff.writeUInt16LE(value,offset+8);else tiff.writeUInt32LE(value,offset+8);};
  const make=ascii('Pocket Camera'),model=ascii('DeskCam 42'),software=ascii('Fixture Editor'),artist=ascii('Ada Example'),date=ascii('2024:03:12 14:05:06'),serial=ascii('BODY-12345');
  const lat=rationals([37,46,30]),lon=rationals([122,25,10]);
  tiff.writeUInt16LE(7,ifd0);let e=ifd0+2;for(const spec of [[0x010f,2,make.count,make.offset],[0x0110,2,model.count,model.offset],[0x0112,3,1,6],[0x0131,2,software.count,software.offset],[0x013b,2,artist.count,artist.offset],[0x8769,4,1,exifIfd],[0x8825,4,1,gpsIfd]] as const){entry(e,spec[0],spec[1],spec[2],spec[3]);e+=12;}tiff.writeUInt32LE(0,e);
  tiff.writeUInt16LE(2,exifIfd);e=exifIfd+2;for(const spec of [[0x9003,2,date.count,date.offset],[0xa431,2,serial.count,serial.offset]] as const){entry(e,spec[0],spec[1],spec[2],spec[3]);e+=12;}tiff.writeUInt32LE(0,e);
  tiff.writeUInt16LE(4,gpsIfd);e=gpsIfd+2;entry(e,1,2,2,'N\0');entry(e+12,2,5,3,lat);entry(e+24,3,2,2,'W\0');entry(e+36,4,5,3,lon);tiff.writeUInt32LE(0,e+48);
  const payload=Buffer.concat([Buffer.from('Exif\0\0','binary'),tiff.subarray(0,cursor)]);const length=Buffer.alloc(2);length.writeUInt16BE(payload.length+2);return Buffer.concat([jpeg.subarray(0,2),Buffer.from([0xff,0xe1]),length,payload,jpeg.subarray(2)]);
}

async function open(page:Page){await page.goto('/image-privacy-checker/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(document.querySelector('astro-island:not([ssr])')));await page.locator('input[type=file]').waitFor({state:'attached'});}
async function upload(page:Page,name:string,buffer:Buffer,mimeType='image/png'){await page.locator('input[type=file]').setInputFiles({name,buffer,mimeType});}
async function ready(page:Page,cancelDeep=true){
  await expect(page.locator('.privacy-scoreboard')).toBeVisible({timeout:15_000});
  const cancel=page.getByRole('button',{name:'Cancel full scan'});
  if(cancelDeep&&await cancel.isVisible().catch(()=>false)){await cancel.click();await expect(cancel).toBeHidden();}
}
async function complete(page:Page){await expect(page.getByRole('button',{name:'Download JSON report'})).toBeEnabled({timeout:30_000});}

test('privacy checker page is accessible and advertises local processing',async({page})=>{await open(page);await expect(page.getByRole('heading',{name:'Image Privacy Checker'})).toBeVisible();await expect(page.getByText('Your files never leave your device.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Choose an image'})).toBeVisible();});
test('uses the requested page title and exact input accept list',async({page})=>{await open(page);await expect(page).toHaveTitle('Image Privacy Checker – Detect EXIF, GPS and Hidden Metadata');await expect(page.locator('input[type=file]')).toHaveAttribute('accept','image/jpeg,image/png,image/webp');});
test('checks a no-metadata PNG and reports score zero without a safety claim',async({page})=>{await open(page);await upload(page,'plain.png',png());await ready(page);await expect(page.locator('.privacy-score-number strong')).toHaveText('0');await expect(page.locator('.privacy-score-reading h2')).toHaveText('Low');await expect(page.getByText('No supported privacy-sensitive metadata was detected.').first()).toBeVisible();await expect(page.getByText(/completely safe/i)).toHaveCount(0);});
test('keeps a clean PNG at zero after the automatic full scan and excludes host/runtime fields',async({page})=>{test.setTimeout(60_000);await open(page);await upload(page,'clean-canvas.png',png());await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await expect(page.locator('.privacy-score-number strong')).toHaveText('0');await expect(page.locator('.privacy-risk-card')).toHaveCount(0);await expect(page.getByText(/FileDeviceID|FileModifyDate|NewGUID/)).toHaveCount(0);});
test('shows basic file facts even when no supported risk is found',async({page})=>{await open(page);await upload(page,'plain.png',png());await ready(page);await expect(page.getByText('plain.png',{exact:true})).toBeVisible();await expect(page.getByText('2 × 1')).toBeVisible();await expect(page.getByText('PNG',{exact:true}).first()).toBeVisible();});
test('checks a real JPEG with GPS and raises a precise-location risk',async({page})=>{await open(page);await upload(page,'camera.jpg',gpsJpeg(await canvasJpeg(page)),'image/jpeg');await ready(page);await expect(page.getByRole('heading',{name:'Precise GPS coordinates'})).toBeVisible();await expect(page.locator('#risk-precise-location')).toContainText('+40');await expect(page.locator('.privacy-score-reading h2')).toHaveText('Critical');});
test('shows privacy score, scan state, risk count, high count, and sensitive field count',async({page})=>{await open(page);await upload(page,'author.png',png([['Artist','Ada Example'],['Email','ada@example.test']]));await ready(page);await expect(page.getByText('Privacy score',{exact:true})).toBeVisible();await expect(page.locator('.privacy-score-reading .eyebrow')).toContainText(/Full scan (running|incomplete)/i);for(const label of ['Risks','High priority','Sensitive fields'])await expect(page.getByText(label,{exact:true})).toBeVisible();});
test('renders explainable risk cards with recommendation and contribution',async({page})=>{await open(page);await upload(page,'author.png',png([['Artist','Ada Example']]));await ready(page);const card=page.locator('#risk-creator-identity');await expect(card).toContainText('Author or creator name');await expect(card).toContainText('Why this matters');await expect(card).toContainText('Recommended action');await expect(card).toContainText('+15');});
test('expands detected fields and provides an explicit masked-value copy control',async({page})=>{await open(page);await upload(page,'author.png',png([['Artist','Ada Example']]));await ready(page);await page.locator('#risk-creator-identity summary').click();await expect(page.locator('#risk-creator-identity code')).toHaveText('A***');await expect(page.locator('#risk-creator-identity').getByRole('button',{name:'Copy masked value'})).toBeVisible();await expect(page.locator('#risk-creator-identity')).toContainText('Metadata evidence');});
test('category filters operate on the current report',async({page})=>{await open(page);await upload(page,'mixed.png',png([['Artist','Ada Example'],['Software','Fixture Editor']]));await ready(page);await page.getByRole('button',{name:'Identity'}).click();await expect(page.getByRole('button',{name:'Identity'})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('heading',{name:'Author or creator name'})).toBeVisible();await expect(page.getByRole('heading',{name:'Editing software'})).toHaveCount(0);});
test('severity filters expose selected state and hide other severities',async({page})=>{await open(page);await upload(page,'identity.png',png([['Artist','Ada Example'],['Email','ada@example.test']]));await ready(page);await page.getByRole('button',{name:'Medium'}).click();await expect(page.getByRole('button',{name:'Medium'})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('heading',{name:'Author or creator name'})).toBeVisible();await expect(page.getByRole('heading',{name:'Email or contact information'})).toHaveCount(0);});
test('search covers risk titles, field paths, and values without reparsing',async({page})=>{await open(page);await upload(page,'search.png',png([['Artist','Ada Example'],['Software','Fixture Editor']]));await ready(page);const search=page.getByRole('searchbox',{name:'Search risks and fields'});await search.fill('Artist');await expect(page.getByRole('heading',{name:'Author or creator name'})).toBeVisible();await expect(page.getByRole('heading',{name:'Editing software'})).toHaveCount(0);await search.fill('no-such-risk');await expect(page.getByText('No risks match this search.')).toBeVisible();});
test('application parameter and workflow fields do not create a dedicated privacy risk',async({page})=>{await open(page);await upload(page,'application-data.png',png([['parameters','orange cat, Steps: 12, Seed: 42'],['workflow','{"1":{"class_type":"Sampler"}}']]));await ready(page);await expect(page.locator('.privacy-score-number strong')).toHaveText('0');await expect(page.locator('.privacy-risk-card')).toHaveCount(0);await expect(page.getByRole('button',{name:'AI data'})).toHaveCount(0);});
test('initial results appear before the delayed automatic ExifTool full scan',async({page})=>{test.setTimeout(60_000);let release!:()=>void;const gate=new Promise<void>((resolve)=>{release=resolve;});const wasmRequests:string[]=[];await page.route('**/*.wasm',async(route)=>{wasmRequests.push(route.request().url());await gate;await route.continue();});await open(page);expect(wasmRequests).toHaveLength(0);await upload(page,'progressive.png',png([['Artist','Ada']]));await ready(page,false);await expect(page.locator('.privacy-score-reading .eyebrow')).toContainText('Full scan running');await expect(page.getByRole('button',{name:'Download JSON report'})).toBeDisabled();await expect.poll(()=>wasmRequests.length,{timeout:10_000}).toBeGreaterThan(0);release();await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await expect(page.getByRole('button',{name:'Download JSON report'})).toBeEnabled();});
test('a canceled full scan leaves the browser result usable and can be retried',async({page})=>{test.setTimeout(60_000);await open(page);await upload(page,'retry.png',png([['Artist','Ada']]));await ready(page);await expect(page.locator('.privacy-score-reading .eyebrow')).toContainText('Full scan incomplete');await expect(page.getByRole('button',{name:'Retry full scan'})).toBeVisible();await page.getByRole('button',{name:'Retry full scan'}).click();await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});});
test('one automatic full scan replaces standard and embedded stage controls',async({page})=>{test.setTimeout(75_000);await open(page);await upload(page,'embedded.png',png([['Artist','Ada']]));await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:35_000});await expect(page.locator('.privacy-score-reading .eyebrow')).toContainText('Full scan complete');await expect(page.getByRole('button',{name:/Scan embedded data|Retry standard scan/})).toHaveCount(0);await expect(page.locator('.privacy-engine-rail ol')).toHaveCount(0);});
test('downloads a safe schema 1.3 JSON privacy report with the required filename',async({page})=>{await open(page);await upload(page,'My Original.png',png([['Artist','Ada']]));await ready(page);await complete(page);const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download JSON report'}).click();const download=await event;expect(download.suggestedFilename()).toBe('My-Original.privacy-report.json');const path=await download.path();const data=JSON.parse(await readFile(path!,'utf8'));expect(Object.keys(data)).toEqual(['version','evidencePolicyVersion','generatedAt','file','completeness','engines','score','level','scoreTimeline','sourceStats','fieldStats','summary','detectedFieldCount','sensitiveFieldCount','risks','warnings','scanWarnings','disclaimer']);expect(data).toMatchObject({version:'1.3',evidencePolicyVersion:'1.1'});expect(JSON.stringify(data)).not.toMatch(/rawValue|blob:|worker/i);});
test('copies the visible report summary while the full scan is incomplete',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await open(page);await upload(page,'copy.png',png([['Artist','Ada']]));await ready(page);await page.getByRole('button',{name:'Copy visible summary'}).click();await expect(page.getByText('Visible report summary copied.')).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('Full scan incomplete');});
test('copies the full safe schema 1.3 JSON report',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await open(page);await upload(page,'copy.png',png([['Artist','Ada']]));await ready(page);await complete(page);await page.getByRole('button',{name:'Copy complete JSON'}).click();await expect(page.getByText('Full safe JSON report copied.')).toBeVisible();expect(JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()))).toMatchObject({version:'1.3',evidencePolicyVersion:'1.1',file:{name:'copy.png'},completeness:'quick'});});
test('clear terminates work and returns focus to the file button',async({page})=>{await open(page);await upload(page,'reset.png',png([['Artist','Ada']]));await ready(page);await page.getByRole('button',{name:'Clear'}).click();const choose=page.getByRole('button',{name:'Choose an image'});await expect(choose).toBeVisible();await expect(choose).toBeFocused();await expect(page.getByText('reset.png',{exact:true})).toHaveCount(0);});
test('rapid consecutive selection ignores the stale result',async({page})=>{await open(page);const input=page.locator('input[type=file]');await input.setInputFiles({name:'old.png',buffer:png([['parameters','x'.repeat(100_000)]]),mimeType:'image/png'});await input.setInputFiles({name:'new.png',buffer:png([['Artist','Newest']]),mimeType:'image/png'});await ready(page);await expect(page.getByText('new.png',{exact:true})).toBeVisible();await expect(page.getByText('old.png',{exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Author or creator name'})).toBeVisible();});
test('a corrupt PNG reports a stable parse error',async({page})=>{await open(page);const broken=png();broken.writeUInt32BE(0xfffffff0,8);await upload(page,'broken.png',broken);await expect(page.getByRole('alert')).toContainText('CORRUPTED_FILE');});
test('an unsupported file signature reports an error',async({page})=>{await open(page);await upload(page,'animation.gif',Buffer.from('GIF89a'),'image/gif');await expect(page.getByRole('alert')).toContainText(/UNSUPPORTED|INVALID_FILE_SIGNATURE/);});
test('keyboard Enter opens the picker and completes a check',async({page})=>{await open(page);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose an image'}).press('Enter');const fileChooser=await chooser;await fileChooser.setFiles({name:'keyboard.png',buffer:png(),mimeType:'image/png'});await ready(page);await expect(page.getByText('keyboard.png',{exact:true})).toBeVisible();});
test('keyboard Space opens the picker',async({page})=>{await open(page);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose an image'}).press('Space');const fileChooser=await chooser;await fileChooser.setFiles({name:'space.png',buffer:png(),mimeType:'image/png'});await ready(page);});
test('mobile report has no obvious horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await open(page);await upload(page,'mobile.png',png([['Artist','Ada'],['Email','ada@example.test']]));await ready(page);const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(width.scroll).toBeLessThanOrEqual(width.client+1);});
test('desktop and mobile visual checkpoints render without console errors',async({page},testInfo)=>{const errors:string[]=[];page.on('console',(message)=>{if(message.type()==='error')errors.push(message.text());});await page.setViewportSize({width:1440,height:1000});await open(page);await upload(page,'visual-check.png',png([['Artist','Ada Example'],['Email','ada@example.test'],['parameters','orange cat, studio light\nSteps: 12, Sampler: Euler, Seed: 42']]));await ready(page);await page.locator('.privacy-result-actions').scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('desktop-privacy.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.locator('.privacy-result-actions').scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath('mobile-privacy.png'),fullPage:false});expect(errors).toEqual([]);});
test('cleanup is available in-page and keeps the one-purpose remover route',async({page})=>{await open(page);await upload(page,'remove.png',png([['Artist','Ada']]));await ready(page);await expect(page.getByRole('heading',{name:'Make a cleaner copy. Then challenge it again.'})).toBeVisible();await expect(page.getByRole('link',{name:'Image Metadata Remover is available'})).toHaveAttribute('href','/image-metadata-remover/');});
test('privacy-first cleanup creates, fully rescans, diffs, and downloads a clean PNG plus receipt',async({page})=>{test.setTimeout(90_000);await open(page);await upload(page,'clean me.png',png([['Artist','Ada']]));await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await page.getByRole('button',{name:'Create and verify clean copy'}).click();await expect(page.locator('.privacy-cleanup-result')).toBeVisible({timeout:45_000});await expect(page.locator('.privacy-cleanup-result')).toContainText('15 → 0');const cleanEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download clean copy'}).click();expect((await cleanEvent).suggestedFilename()).toBe('clean-me-clean.png');const receiptEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download cleanup receipt'}).click();const receipt=await receiptEvent;expect(receipt.suggestedFilename()).toBe('clean-me-clean.privacy-cleanup.json');const receiptPath=await receipt.path();const data=JSON.parse(await readFile(receiptPath!,'utf8'));expect(data).toMatchObject({schemaVersion:'1.1',mode:'privacy-first',verificationDepth:'embedded'});expect(JSON.stringify(data)).not.toMatch(/rawValue|blob:|ArrayBuffer/i);});
test('preserve-encoding cleanup uses ExifTool and reports verification honestly',async({page})=>{test.setTimeout(90_000);await open(page);await upload(page,'preserve.png',png([['Artist','Ada']]));await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await page.getByRole('radio',{name:/Preserve encoding/}).click();await page.getByRole('button',{name:'Create and verify clean copy'}).click();await expect(page.locator('.privacy-cleanup-result')).toBeVisible({timeout:50_000});await expect(page.locator('.privacy-cleanup-result')).toContainText('preserve-encoding');await expect(page.getByRole('button',{name:'Download clean copy'})).toBeEnabled();});
test('preserve-encoding removes GPS and identifiers while keeping EXIF orientation',async({page})=>{test.setTimeout(120_000);await open(page);await upload(page,'gps-oriented.jpg',gpsJpeg(await canvasJpeg(page)),'image/jpeg');await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await expect(page.getByRole('heading',{name:'Precise GPS coordinates'})).toBeVisible();await page.getByRole('radio',{name:/Preserve encoding/}).click();await page.getByRole('button',{name:'Create and verify clean copy'}).click();const result=page.locator('.privacy-cleanup-result');await expect(result).toBeVisible({timeout:50_000});await expect(result).toContainText('Orientation remains 6.');const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download cleanup receipt'}).click();const download=await event;const receipt=JSON.parse(await readFile((await download.path())!,'utf8'));expect(receipt.afterReport.risks.map((risk:{id:string})=>risk.id)).toEqual(['rights-information']);await expect(result).toContainText('100 → 8');await expect(page.getByRole('button',{name:'Download clean copy'})).toBeEnabled();});
test('APNG disables pixel re-encoding so its frames are not flattened',async({page})=>{await open(page);await upload(page,'animated.png',apng());await ready(page);await expect(page.getByRole('radio',{name:/Privacy-first/})).toBeDisabled();await expect(page.getByRole('radio',{name:/Preserve encoding/})).toHaveAttribute('aria-checked','true');await expect(page.getByText('Animated',{exact:true})).toBeVisible();});
test('a Remover download gets the same zero score when uploaded to Privacy Checker',async({page})=>{test.setTimeout(120_000);await page.goto('/image-metadata-remover/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(document.querySelector('astro-island:not([ssr])')));await page.locator('input[type=file]').setInputFiles({name:'private.png',buffer:png([['Artist','Ada'],['Email','ada@example.test'],['parameters','orange cat, Seed: 42']]),mimeType:'image/png'});await expect(page.getByText('Ready to create a clean copy')).toBeVisible({timeout:30_000});await page.getByRole('button',{name:'Create and verify clean copy'}).click();await expect(page.locator('.removal-result')).toBeVisible({timeout:45_000});const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download clean copy'}).click();const downloaded=await event;const path=await downloaded.path();expect(path).toBeTruthy();const cleanBytes=await readFile(path!);await open(page);await upload(page,'private-clean.png',cleanBytes);await ready(page,false);await expect(page.locator('.privacy-engine-rail h2')).toHaveText('Full scan complete',{timeout:30_000});await expect(page.locator('.privacy-score-number strong')).toHaveText('0');await expect(page.locator('.privacy-risk-card')).toHaveCount(0);});
test('View all metadata uses the correct route and explains reselection',async({page})=>{await open(page);await upload(page,'inspect.png',png([['Artist','Ada']]));await ready(page);await expect(page.getByRole('link',{name:/View all image metadata/})).toHaveAttribute('href','/image-metadata-viewer/');await expect(page.locator('.privacy-detected-data').getByText(/select the image again/i)).toBeVisible();});
test('multiple files are handled explicitly and only the first is checked',async({page})=>{await open(page);await page.locator('input[type=file]').setInputFiles([{name:'first.png',buffer:png(),mimeType:'image/png'},{name:'second.png',buffer:png([['Artist','Second']]),mimeType:'image/png'}]);await ready(page);await expect(page.getByText(/You chose 2 files/)).toBeVisible();await expect(page.getByText('first.png',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Author or creator name'})).toHaveCount(0);});
test('files over 50 MB stop before a report is created',async({page})=>{test.setTimeout(45_000);await open(page);await page.evaluate(()=>{const file=new File([new Uint8Array(50*1024*1024+1)],'huge.png',{type:'image/png'});const transfer=new DataTransfer();transfer.items.add(file);document.querySelector<HTMLElement>('.privacy-dropzone')!.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}));});await expect(page.getByRole('alert')).toContainText('FILE_TOO_LARGE',{timeout:25_000});await expect(page.locator('.privacy-scoreboard')).toHaveCount(0);});
test('checking sensitive metadata sends no sensitive request data',async({page})=>{await open(page);const requests:string[]=[];page.on('request',(request)=>requests.push(`${request.method()} ${request.url()} ${request.postData()??''}`));await upload(page,'private-filename.png',png([['Artist','Ada Private'],['Email','ada@example.test'],['parameters','private prompt Seed: 42']]));await ready(page);const traffic=requests.join('\n');expect(traffic).not.toMatch(/private-filename|Ada Private|ada@example\.test|private prompt|BODY-12345|37\.775/i);expect(requests.filter((item)=>!/^(GET|HEAD) /.test(item))).toEqual([]);});
test('result includes the explicit visible-content limitation',async({page})=>{await open(page);await upload(page,'limits.png',png());await ready(page);await expect(page.locator('.privacy-honest-limit').getByText('This tool checks embedded metadata only. It does not analyze visible image content.')).toBeVisible();});
