import type { ToolEditorialLocaleCopy } from './tool-editorial-types';

export const toolEditorialDe: ToolEditorialLocaleCopy = {
  home: [],
  metadata: [
    { id: 'all-fields-context', title: 'Erst die Feldgruppe lesen, dann den Wert einordnen', paragraphs: [
      'Ein Feld namens Creator bedeutet in einem PDF etwas anderes als ein Künstlername in einer Audiodatei. Schau deshalb zuerst auf das erkannte Format und den Pfad neben dem Wert. Eine Bilddatei kann EXIF, XMP und IPTC gleichzeitig enthalten. Bei einem PDF können Info und XMP unterschiedliche Autoren nennen. Der vollständige Bericht hält diese Gruppen auseinander, statt aus mehreren Angaben eine scheinbar eindeutige Geschichte zu bauen.',
      'Formuliere deine Frage vor der Suche. Geht es um einen privaten Ort, suche nach GPS und Ortsangaben. Für einen Dokumentautor prüfst du Autor, Ersteller, Firma und benutzerdefinierte Eigenschaften. Bei einem Medienexport vergleichst du außerdem Dauer, Codec und Spuren. Ein Suchtreffer allein ist noch kein Befund: Lies seinen Wert, seine Gruppe und die Warnungen. So kannst du erklären, was diese konkrete Kopie tatsächlich enthält.',
    ], fields: [
      { name: 'EXIF / XMP / IPTC', meaning: 'Bildfelder können Aufnahmeinstellungen, Beschreibungen und Bearbeitungsangaben speichern.', caveat: 'Mehrere Gruppen dürfen unterschiedliche Daten oder Namen enthalten. Bewahre die Pfade beim Vergleich.' },
      { name: 'PDF Info / Office', meaning: 'Dokumentprogramme speichern Titel, Autoren, Datumswerte und eigene Eigenschaften.', caveat: 'Diese Eigenschaften erfassen nicht alle Namen im Text, in Kommentaren oder in Anhängen.' },
      { name: 'ID3 / Vorbis / RIFF', meaning: 'Audiolabels enthalten etwa Titel, Interpret, Notizen und Softwareangaben.', caveat: 'Solche Texte lassen sich ändern, ohne den gesprochenen oder gespielten Inhalt zu ändern.' },
      { name: 'Container / Spuren', meaning: 'Medienheader beschreiben die für Wiedergabe nötigen Codecs und Zeitachsen.', caveat: 'Das Erstellungsdatum eines Containers muss kein Aufnahmedatum sein.' },
    ] },
    { id: 'all-writers', title: 'Welche Programme haben die Angaben hinterlassen?', paragraphs: [
      'Kamera, Telefon, Aufnahmeprogramm, Office-Anwendung und Exportwerkzeug können jeweils eigene Felder schreiben. Ein späterer Bearbeiter kann Werte kopieren, ersetzen oder löschen. Ein Firmenname stammt vielleicht noch aus einer Vorlage. Eine Softwareangabe kann den letzten Export beschreiben und nicht das Gerät, das die Aufnahme gemacht hat. Dieser Viewer liest den heutigen Dateiinhalt; er rekonstruiert nicht automatisch alle früheren Bearbeitungsschritte oder die Personen hinter ihnen.',
      'Halte eingebettete Angaben und die Dateiverwaltung auseinander. Beim Herunterladen kann eine Datei ein neues lokales Datum bekommen, obwohl ihr eingebettetes Aufnahmedatum gleich bleibt. Ein Katalog oder eine separate Begleitdatei kann Stichwörter behalten, die im Export fehlen. Wenn zwei Anwendungen unterschiedliche Werte zeigen, öffne zuerst genau dieselben Dateibytes. Prüfe danach native Gruppen und Exportweg. Unterschiedliche Anzeigen allein beweisen weder einen Fehler noch eine Manipulation.',
    ] },
    { id: 'all-reading-limits', title: 'Fehlend ist etwas anderes als nicht vollständig gelesen', paragraphs: [
      'Warte auf den vollständigen Scan und lies die Hinweise. Ein danach fehlendes Feld wurde in dieser Kopie nicht gefunden. Daraus folgt nicht, ob das Gerät es nie gespeichert hat, ein Editor es entfernt hat oder ein Katalog es noch außerhalb der Datei hält. Vergleiche bei Bedarf eine andere eigene Originaldatei. Das wiederholte Auswählen derselben Kopie oder eine neue Dateiendung schafft keine verlorenen Angaben zurück.',
      'Ein abgebrochener Parser, ein geschütztes Dokument oder ein beschädigter Container ist eine Lesegrenze. Bewahre das Original und notiere den erkannten Typ sowie die Diagnose. Eine leere Zusammenfassung während eines solchen Fehlers belegt keine Metadatenfreiheit. Die spezialisierten Viewer erklären die unterstützten Formate genauer. Eine signierte Herkunft prüfst du separat mit C2PA. Namen, Daten und Koordinaten in gewöhnlichen Metadaten sind veränderbare Angaben und ersetzen diese Prüfung nicht.',
    ] },
    { id: 'all-controlled-example', title: 'Lerne die Suche an einer gekennzeichneten Beispieldatei', paragraphs: [
      'Das optionale Bildbeispiel trägt absichtlich gesetzte Demonstrationswerte: ViewExif als Hersteller, Demo Camera als Modell und ViewExif Demo als Künstler. Das Beispieldatum lautet 2026:01:15 10:30:00. Das Bild entstand mit KI; die Kamerafelder belegen keine echte Aufnahme. Auch die Koordinaten des öffentlichen Eiffelturm-Wahrzeichens dienen nur zum Erklären eines Felds. Sie behaupten keinen tatsächlichen Standort einer Kamera oder einer Privatperson.',
      'Suche einen dieser Werte im vollständigen Bericht und notiere seinen Pfad. Wenn du anschließend eine bereinigte Kopie erstellst, öffne die heruntergeladene Ausgabe erneut im passenden Viewer. Ein neuer Hash zeigt veränderte Bytes, aber nicht die Entfernung eines bestimmten Werts. Lies verbliebene Felder und Prüfumfang getrennt. Für deine eigene Datei gilt außerdem: Bild, Sprache, Text und Dateiname können Informationen verraten, die dieser Metadatenbericht nicht beurteilt.',
    ], figure: { src: '/editorial/image-sample.png', alt: 'Lokaler Bildbericht mit markierten synthetischen Demonstrationswerten', caption: 'Absichtlich gesetzte Felder erklären die Quelle eines Werts. Sie belegen keine echte Kameraaufnahme oder einen realen Fotografen.' } },
  ],
  image: [
    { id: 'image-fields-context', title: 'Welche Bildfelder beantworten deine Frage?', paragraphs: [
      'Eine Bilddatei enthält nicht nur eine einzige Liste mit Kameradaten. EXIF kann Aufnahmeparameter speichern, XMP kann Bearbeitungs- und Autorenangaben tragen, IPTC kann Bildbeschreibungen und Credits enthalten. PNG und andere Formate können außerdem Textfelder haben. Suche deshalb in den nativen Gruppen, wenn die Zusammenfassung einen gesuchten Wert nicht zeigt. Die Feldfamilie hilft dir, einen Treffer zu verstehen; die Schreibweise des Namens allein reicht dafür nicht.',
      'Für eine Ortsfrage prüfst du GPS und andere lesbare Ortsangaben. Für einen Autor suchst du Künstler, Creator, By-line und Kontaktfelder. Für korrekte Darstellung schaust du auf Orientierung und Farbprofil. Diese Ziele unterscheiden sich: Eine private Koordinate ist ein anderer Befund als ein ICC-Profil. Ein Feld kann für die Darstellung nötig sein, obwohl es nach einer Bereinigung weiterhin im Bericht erscheint.',
    ], fields: [
      { name: 'DateTimeOriginal', meaning: 'Eine Kamera oder Anwendung kann hier das Aufnahmedatum ablegen.', caveat: 'Der Wert ist veränderbar; eine Zeitzone fehlt bei vielen Dateien.' },
      { name: 'Artist / creator / by-line', meaning: 'Mehrere Feldfamilien können Namen oder Credits enthalten.', caveat: 'Ein Name belegt weder Urheberschaft noch Einwilligung der abgebildeten Person.' },
      { name: 'GPS / Ortsangaben', meaning: 'Geräte oder Apps können einen Ort in verschiedenen Schreibweisen speichern.', caveat: 'Eine Kopie kann alte oder geänderte Koordinaten tragen.' },
      { name: 'Orientation / ICC', meaning: 'Diese Angaben helfen bei Bildausrichtung und Farbdarstellung.', caveat: 'Sie sind nicht automatisch ein übrig gebliebener privater Hinweis.' },
    ] },
    { id: 'image-writers', title: 'Kameraangaben und Exportspuren auseinanderhalten', paragraphs: [
      'Eine Kamera kann ihr Modell und Belichtungswerte schreiben. Ein Bildeditor kann später XMP ergänzen oder beim Export ganze Feldgruppen weglassen. Eine Veröffentlichungssoftware kann zusätzlich Titel, Rechte oder Credits setzen. Auch eine Vorlage oder ein kopiertes Profil kann alte Namen mitbringen. Der Bericht zeigt die Angaben der gewählten Kopie. Er kann nicht garantieren, welches Programm einen Wert ursprünglich schrieb oder ob dieser damals zutraf.',
      'Vergleiche bei widersprüchlichen Anzeigen zunächst dieselbe Datei, nicht ein Original mit einer heruntergeladenen Vorschau. Eine Fotobibliothek kann Beschreibungen in ihrem Katalog halten. Ein Export kann sie übernehmen oder verlieren. Das lokale Dateidatum kann sich beim Kopieren ändern, ohne EXIF zu ändern. Notiere den Exportweg und die Feldpfade, bevor du ein Datum, einen Kameranamen oder eine Softwareangabe als Aufnahmebeweis verwendest.',
    ] },
    { id: 'image-reading-limits', title: 'Keine Vorschau heißt nicht keine Metadaten', paragraphs: [
      'Ein Browser kann für HEIC oder TIFF unter Umständen keine Pixelvorschau anzeigen, obwohl Metadaten lesbar sind. Warte deshalb auf den vollständigen Scan und unterscheide Vorschaufehler von einer Parserwarnung. Fehlt danach ein Kameramodell, wurde es in dieser Kopie nicht gefunden. Der Bericht kann nicht entscheiden, ob die Kamera es nie schrieb, ein Editor es entfernte oder eine andere Originalkopie es noch besitzt.',
      'Bei einem beschädigten Block oder abgebrochenen Scan bleibt die Lesegrenze wichtig. Nenne eine solche Datei nicht metadatenfrei. Bewahre das Original und prüfe eine unterstützte Kopie, die du selbst erzeugen darfst. Ein Umbenennen der Endung repariert den Inhalt nicht. Gesichter, Straßenschilder, Spiegelungen und Bildschirmtexte gehören zu den Pixeln; dieser Viewer analysiert sie nicht. Dafür braucht die geplante Veröffentlichung eine eigene Sichtprüfung.',
    ] },
    { id: 'image-native-example', title: 'Ein Kamerafeld am Beispiel verfolgen', paragraphs: [
      'Das gekennzeichnete Beispielbild besitzt die Werte Make = ViewExif, Model = Demo Camera und Artist = ViewExif Demo. Alle Kamerawerte wurden absichtlich hinzugefügt; das Bild selbst ist KI-generiert. Suche den Künstlerwert in den vollständigen Feldern und halte seine Gruppe fest. Vergleiche anschließend die Angaben zur Bildgröße und Orientierung. So lernst du, beschreibende Labels von technischen Darstellungsfeldern zu unterscheiden, ohne ein privates Foto zu verwenden.',
      'Für einen Vorher-nachher-Vergleich kannst du die Beispieldatei ausdrücklich an den Bildreiniger weitergeben. Starte die Bereinigung selbst, warte auf die Prüfung und öffne die tatsächlich heruntergeladene Kopie erneut. Suche denselben Wert mit demselben Pfad. Ein anderer Hash ist nach Änderungen normal, belegt aber keine vollständige Anonymität. Notiere verbleibende Werte und Grenzen; das Beispiel darf keine echte Kameraaufnahme oder einen realen Fotografen vortäuschen.',
    ], figure: { src: '/editorial/image-sample.png', alt: 'Bildbericht mit gekennzeichneten synthetischen Kamerafeldern', caption: 'Ein kontrolliertes Beispiel mit absichtlich hinzugefügten Werten. Bild und Kameradaten behaupten keine tatsächliche fotografische Aufnahme.' } },
  ],
  document: [
    { id: 'document-property-table', title: 'PDF- und Office-Eigenschaften getrennt vergleichen', paragraphs: [
      'Ein PDF kann einen Titel im Info-Wörterbuch und zusätzlich in XMP besitzen. Ein DOCX, PPTX oder XLSX speichert dagegen Kern-, Anwendungs- und optionale eigene Eigenschaften in einem Paket. Die Gruppen beschreiben dieselbe Datei aus verschiedenen Blickwinkeln. ViewExif hält ihre Pfade sichtbar. Wenn zwei Autorenwerte voneinander abweichen, musst du deshalb nicht sofort einen davon zum richtigen erklären; prüfe zuerst seine Quelle und den Exportweg.',
      'Wähle die Eigenschaften passend zu deinem Vorhaben. Vor einer öffentlichen Weitergabe suchst du etwa nach Autor, Firma, Ersteller und eigenen Projektfeldern. Für eine technische Übergabe interessieren vielleicht Seiten, Folien oder Arbeitsblätter. Gespeicherte Zähler können veraltet sein und sind kein neu berechneter Inhalt. Dieser Viewer extrahiert weder den Dokumenttext noch Zellen, Folientexte oder Anhänge. Seine Aussagen betreffen Eigenschaften und sicher lesbare Paketstatistiken.',
    ], fields: [
      { name: 'Author / dc:creator', meaning: 'PDF Info und XMP können getrennte Autorenangaben speichern.', caveat: 'Unterschiedliche Werte sind Hinweise auf einen Arbeitsablauf, keine Urheberschaftsbeweise.' },
      { name: 'Creator / Producer', meaning: 'Diese Felder nennen oft an Erstellung oder Export beteiligte Programme.', caveat: 'Ein Programmname identifiziert nicht die Person, die den Text schrieb.' },
      { name: 'Core / App / Custom', meaning: 'Office trennt Beschreibung, Anwendungseigenschaften und eigene Felder.', caveat: 'Ein alter Firmenname kann neben einem neuen sichtbaren Titel bestehen bleiben.' },
      { name: 'Revision / Statistiken', meaning: 'Manche Anwendungen speichern Bearbeitungszähler und Dokumentzahlen.', caveat: 'Ein gespeicherter Zähler ist kein vollständiges Änderungsprotokoll.' },
    ] },
    { id: 'document-writers', title: 'Woher kommen alte Autoren und Firmennamen?', paragraphs: [
      'Eine Office-Anwendung kann den Autor aus einem Benutzerprofil übernehmen. Eine Vorlage kann Firmen- und Projektwerte mitbringen. Beim PDF-Export kann das Programm diese Angaben weitertragen und zusätzlich eigene Ersteller- oder Producer-Labels ergänzen. Ein späterer Bearbeiter ändert vielleicht den sichtbaren Titel, ohne die benutzerdefinierten Eigenschaften anzufassen. Suche daher in allen vorhandenen Gruppen, wenn die Datei an einen neuen Empfängerkreis gehen soll.',
      'Auch hier unterscheiden sich eingebettete Werte und lokale Dateiverwaltung. Ein frisch heruntergeladenes Dokument kann ein neues Dateidatum haben, während seine internen Eigenschaften ältere Daten zeigen. Beide Beobachtungen können gleichzeitig stimmen. Prüfe dieselbe Dateikopie in beiden Anwendungen, bewahre die nativen Pfade und notiere den Exportweg. Ein Datum oder Name allein erzählt nicht die vollständige Geschichte einer Vorlage, eines Exports oder mehrerer Mitautoren.',
    ] },
    { id: 'document-reading-limits', title: 'Ein geschütztes Dokument ist kein leerer Bericht', paragraphs: [
      'Ein nach vollständiger Analyse fehlender Autor wurde in dieser Kopie nicht gefunden. Ein passwortgeschütztes PDF, beschädigtes Office-Paket oder nicht unterstütztes Altformat ist dagegen eine Lesegrenze. ViewExif entschlüsselt keine geschützten Dateien. Alte DOC-, PPT- und XLS-Dateien werden nicht durch eine neue Endung zu DOCX, PPTX oder XLSX. Bewahre den Ursprung und erzeuge bei vorhandener Berechtigung eine unterstützte Kopie in der passenden Anwendung.',
      'Lies Warnungen vor jeder Schlussfolgerung und suche auch die nativen Felder. Eine unvollständige Analyse darf nicht als Nachweis fehlender Eigenschaften dienen. Falls du eine öffentliche Kopie vorbereitest, prüfe danach sichtbare Namen, Kommentare, Überarbeitungen und Anhänge im Dokument selbst. Diese Inhalte gehören nicht zum hier gelesenen Eigenschaftenbericht. Metadaten können einen Privatsphärehinweis liefern; sie bescheinigen nicht, dass das gesamte Dokument keine persönlichen Angaben enthält.',
    ] },
    { id: 'document-controlled-example', title: 'Eine harmlose Eigenschaft als Suchziel verwenden', paragraphs: [
      'Das kontrollierte DOCX-Beispiel trägt den Titel Synthetic review copy, den Autor Ada Example, die Firma Example Studio und die eigene Eigenschaft Review status mit dem Wert Draft. Vergleiche Kern-, Anwendungs- und eigene Gruppen. Alle Werte sind absichtlich gesetzte Lehrdaten. Das Bildschirmbild zeigt den lokalen Paketbericht und behauptet weder einen echten Autor noch, dass alle Dokumentprogramme dieselben Eigenschaften schreiben. Die sichtbaren Inhalte bleiben eine separate Prüfung.',
      'Nach einer ausdrücklich gestarteten Bereinigung öffnest du die tatsächliche Ausgabedatei erneut und suchst dieselben Pfade. Lies Restfelder und Prüfwarnungen, bevor du sie teilst. Ein anderer Hash zeigt geänderte Bytes, nicht automatisch entfernte Namen. Schau zusätzlich in einem gewöhnlichen PDF-Leser auf Seiteninhalt, Formulare, Kommentare und Anlagen. Bewahre das Original separat, besonders wenn es signiert ist oder einen wichtigen Bearbeitungsstand dokumentiert.',
    ], figure: { src: '/editorial/document-sample.png', alt: 'Lokaler DOCX-Bericht mit markierten Demonstrationseigenschaften', caption: 'Eine synthetische Office-Datei mit Kern-, Anwendungs- und eigenen Eigenschaften. Sichtbarer Text und Anhänge liegen außerhalb dieses Berichts.' } },
  ],
  video: [
    { id: 'video-field-table', title: 'Aufnahmehinweise und Wiedergabestruktur unterscheiden', paragraphs: [
      'Eine Videodatei ist ein Container mit Bild-, Ton- und eventuell weiteren Spuren. MP4 oder MOV können andere Records als MKV, WebM oder AVI speichern. ViewExif prüft die echte Signatur und zeigt lesbare Container- und Spurfelder. Eine kurze Karte zur Dauer ist deshalb nur ein Einstieg. Für eine konkrete Frage suche zusätzlich die nativen Gruppen, etwa nach Ort, Datum, Titel oder dem Programm des letzten Exports.',
      'Dauer, Codec und Abmessungen beschreiben die Wiedergabe. Ein Erstellungsdatum kann dagegen zu einem Container, einer Spur oder einem späteren Export gehören. Diese Angaben dürfen voneinander abweichen. Bevor du damit einen Aufnahmezeitpunkt erklärst, prüfe Gruppe, Zeitzonenhinweise und Dateihistorie. Der Viewer spielt das Video nicht ab und untersucht keine Bilder oder gesprochenen Inhalte. Ein Name im Container ist kein Beweis für die Person vor der Kamera.',
    ], fields: [
      { name: 'CreateDate / Zeitwerte', meaning: 'Container und Spuren können eigene Datumsangaben besitzen.', caveat: 'Ein Exportdatum muss nicht das Datum des Filmens sein.' },
      { name: 'Encoder / Handler', meaning: 'Kameras und Editoren können Software- oder Spurnamen schreiben.', caveat: 'Die Labels lassen sich ändern oder aus einer früheren Datei übernehmen.' },
      { name: 'GPS / Ortsstrings', meaning: 'Manche Aufnahme-Apps speichern lesbare Positionen im Container.', caveat: 'Nicht jede Telemetrie ist ein einzelnes gewöhnliches GPS-Feld.' },
      { name: 'Codec / Spuren / Dauer', meaning: 'Diese Felder beschreiben den Aufbau des abspielbaren Mediums.', caveat: 'Sie beweisen weder einen Aufnahmeort noch die Wahrheit einer Szene.' },
    ] },
    { id: 'video-writers', title: 'Welche Station eines Videoexports beschreibt ein Label?', paragraphs: [
      'Ein Telefon kann Geräte- oder Ortsangaben setzen. Ein Schnittprogramm kann Titel, Encoder und neue Zeitwerte ergänzen. Ein späterer Containerexport kann vorhandene Labels kopieren oder nur einen Teil davon behalten. Ein Programmname im fertigen Video kann deshalb die letzte Station beschreiben statt der ersten. Vergleiche mehrere Gruppen und den bekannten Exportweg, bevor du daraus eine Kamerazuordnung oder eine bestimmte Bearbeitung ableitest.',
      'Wenn ein Player einen anderen Titel zeigt, prüfe, ob er die gleiche Kopie öffnet. Er kann den Dateinamen als Ersatz anzeigen oder einen Wert aus einer anderen Gruppe bevorzugen. Eine Vorschau aus einer Plattform kann außerdem andere Bytes als der ursprüngliche Upload besitzen. Nutze die vollständige Feldsuche und halte den Pfad fest. Ein Widerspruch zwischen zwei Ansichten erklärt sich nicht allein aus der Bezeichnung des Felds.',
    ] },
    { id: 'video-reading-limits', title: 'Eine beschädigte Indexstruktur nicht als fehlende Daten lesen', paragraphs: [
      'Warte bis zur fertigen Analyse. Ein danach nicht gefundenes Datum fehlt im lesbaren Bericht dieser Kopie. Das zeigt nicht, ob die Kamera es nie schrieb oder der Export es entfernte. Ein beschädigter Index, nicht unterstützter Teil des Containers oder abgebrochener Parser begrenzt dagegen die Untersuchung. Eine leere Zusammenfassung in diesem Zustand belegt keine Metadatenfreiheit. Bewahre die Quelle und lies die konkrete Diagnose.',
      'Prüfe bei Bedarf eine unterstützte Kopie, die du selbst erzeugen darfst, und notiere ihre Exportoptionen. Eine geänderte Dateiendung repariert keine Containerstruktur. Der allgemeine Grenzwert schützt außerdem den Tab vor sehr großen oder beschädigten Dateien. Untertitel, sichtbare Gesichter, Ortszeichen und Sprache liegen außerhalb dieser Metadatenanalyse. Selbst ein vollständiger Bericht ohne Ortsfeld kann nicht bescheinigen, dass ein Video seinen Aufnahmeort auf keinem anderen Weg verrät.',
    ] },
    { id: 'video-controlled-example', title: 'Einen Containerwert an einer Testdatei verfolgen', paragraphs: [
      'Die kontrollierte MP4-Datei enthält eine Zeitskala von 1000 und eine Dauer von 1000 Einheiten, aber keine tatsächlichen Medienspuren. Sie demonstriert das Lesen eines Containers und ist kein abspielbares Video. Vergleiche die gemeldeten Headerwerte und halte diese Grenze bei deinen Notizen fest. Das Beispiel zeigt weder eine Kameraaufnahme noch einen Filmtermin. Ein lesbarer Containerheader beweist keine vollständige oder nutzbare Ton- und Bildstruktur.',
      'Für eine eigene echte Aufnahme prüfst du dagegen Containerwerte, Spuren und Parserwarnungen gemeinsam. Halte den tatsächlichen Exportweg fest und öffne nur eine erlaubte, untersuchte Ausgabe. Ein neuer Hash beschreibt veränderte Bytes, nicht die Entfernung eines bestimmten Tags. Ein zusätzlicher Abspieltest gehört zur Nutzbarkeit solcher Medien. Er ist bei diesem bewusst spurfreien Demonstrationscontainer nicht möglich. Die Metadatenprüfung bewertet außerdem weder die Szene noch die Identifizierbarkeit einer Tonspur.',
    ], figure: { src: '/editorial/video-sample.png', alt: 'Metadaten eines synthetischen MP4-Containers ohne Medienspuren', caption: 'Ein Beispiel zum Lesen eines Containers, kein abspielbares Video. Headerwerte belegen weder ein Aufnahmeereignis noch vollständige Medienverifikation.' } },
  ],
  audio: [
    { id: 'audio-tag-table', title: 'Audiolabels getrennt vom Klang lesen', paragraphs: [
      'MP3 nutzt häufig ID3, FLAC Vorbis-Kommentare und WAV kann RIFF INFO, Broadcast-Felder oder iXML enthalten. Ein Recorder, Tag-Editor oder Exportprogramm schreibt diese Records. Ein Player kann einen Titel aus ihnen lesen oder bei fehlendem Tag den Dateinamen anzeigen. Vergleiche deshalb die eingebetteten Werte im Bericht. Die Anzeige eines Players ist kein Nachweis dafür, dass der gleiche Text tatsächlich im Dateiinhalt gespeichert wurde.',
      'Überlege vor der Suche, was du prüfen möchtest. Ein Name oder Kommentar ist ein anderes Ziel als Abtastrate, Kanalzahl oder Dauer. Letztere beschreiben den Audiostream. Ein Coverbild ist ebenfalls ein eigener Inhalt, auch wenn es in einem Tagblock steckt. ViewExif liest vorhandene Felder und sichere Binärzusammenfassungen; das Tool spielt die Aufnahme nicht ab, transkribiert keine Sprache und erkennt keine Menschen anhand ihrer Stimme.',
    ], fields: [
      { name: 'Title / Artist / Album', meaning: 'Beschreibende Tags ordnen eine Aufnahme in Playern und Bibliotheken.', caveat: 'Ein Editor kann diese Texte ändern, ohne Stimme oder Musik zu verändern.' },
      { name: 'Comment / Software / Datum', meaning: 'Recorder und Editoren können Notizen und Exportangaben speichern.', caveat: 'Ein Datum kann zum Tagging oder Export statt zur Aufnahme gehören.' },
      { name: 'Pictures / Artwork', meaning: 'Ein Tagblock kann eingebettete Coverbilder enthalten.', caveat: 'Das Bild kann trotz leerer Textfelder Informationen verraten.' },
      { name: 'Abtastrate / Kanäle', meaning: 'Technische Header beschreiben den für Wiedergabe nötigen Stream.', caveat: 'Diese Werte sind keine gewöhnlichen privaten Textnotizen.' },
    ] },
    { id: 'audio-writers', title: 'Dateitag und Bibliothekseintrag können sich unterscheiden', paragraphs: [
      'Eine Musikbibliothek kann einen älteren Titel in ihrer Datenbank behalten, während die Datei einen neuen Titel oder gar keinen mehr trägt. Manche Programme bevorzugen außerdem eine bestimmte Tagversion. Prüfe zuerst, ob die Anwendungen dieselben Bytes öffnen. Suche anschließend im vollständigen Bericht, statt nur die erste Titelkarte zu vergleichen. Halte die Gruppe eines Werts fest, wenn du ihn nach einer späteren Bearbeitung erneut suchen willst.',
      'Ein Aufnahmeprogramm kann Software und Datum eintragen, ein Bibliothekseditor später Interpret und Album. Ein Export kann einzelne Records kopieren oder ersetzen. Aus einem passenden Namen lässt sich deshalb nicht sicher ableiten, wer die Aufnahme machte oder wem sie gehört. Auch eine fehlerfreie Tagliste belegt keine Zustimmung aller Sprecher. Für eine Veröffentlichung musst du die hörbaren Inhalte, den Dateinamen und mögliche Coverbilder gesondert betrachten.',
    ] },
    { id: 'audio-reading-limits', title: 'Fehlende Tags und beschädigte Tagblöcke unterscheiden', paragraphs: [
      'Warte auf das Ende des Scans. Findet ein vollständiger Bericht keinen Artist, fehlt ein lesbarer entsprechender Wert in dieser Kopie. Das sagt nicht, wer tatsächlich spricht oder spielt. Ein beschädigter Tagblock, ein nicht unterstützter Wrapper oder eine unterbrochene Analyse ist eine andere Lage. Lies die Warnung und bewahre das Original. Eine leere Karte während eines Fehlers darf nicht als vollständige Prüfung ausgegeben werden.',
      'Wenn du eine alternative Kopie brauchst, erzeuge einen unterstützten Export mit vorhandener Berechtigung. Eine neue Endung macht aus einem unlesbaren Format keine gültige MP3-Datei. Vergleiche nur kontrollierte Kopien und halte die Exportoptionen fest. Wiedergabeprobleme und lesbare Tags können außerdem gleichzeitig auftreten: Der Eigenschaftenbericht ersetzt keinen Hörtest. Die allgemeinen Dateigrenzen schützen den Browser, garantieren aber nicht, dass jede Aufnahme innerhalb der Grenze vollständig auswertbar ist.',
    ] },
    { id: 'audio-controlled-example', title: 'Ein absichtlich gesetztes Label verfolgen', paragraphs: [
      'Das kontrollierte WAV-Beispiel trägt den Titel Synthetic silence und Artist = Ada Example. Der Bericht nennt 1,00 Sekunde Mono-PCM mit 8 kHz und 16 Bit. Zugleich bleibt eine Warnung zur Größe des Datenblocks sichtbar, auch wenn der vollständige Scan weitere Felder liefert. Das Beispiel erklärt eine Lesegrenze und ist keine warnungsfreie Aufnahme. Suche das markierte Künstlerlabel und bewahre seine Gruppe zusammen mit dieser Warnung.',
      'Nach einer ausdrücklich gestarteten Bereinigung öffnest du die tatsächlich heruntergeladene Ausgabe hier erneut. Vergleiche die Tags und technischen Header getrennt. Schau auch nach absichtlich erhaltenem Artwork. Ein unveränderter Header beweist nicht, dass alle beschreibenden Records verschwanden. Höre die Ausgabe in deinem eigenen Player an. Ein gelöschtes Künstlerlabel anonymisiert keine Namen, Gespräche oder Ortsangaben, die weiterhin in der hörbaren Aufnahme vorkommen.',
    ], figure: { src: '/editorial/audio-sample.png', alt: 'Audiobericht einer kontrollierten Aufnahme mit Demonstrationstags', caption: 'Ein erzeugtes Audiobeispiel mit markierten Labels. Prüfe echte Feldgruppen statt einer möglicherweise nur aus dem Dateinamen erzeugten Playeranzeige.' } },
  ],
  privacy: [
    { id: 'privacy-field-context', title: 'Welche Hinweise sind für diesen Empfänger relevant?', paragraphs: [
      'Ein genauer Standort kann beim Foto aus der eigenen Wohnung wichtig sein. Eine Seriennummer oder ein Besitzerlabel kann mehrere Dateien demselben Gerät zuordnen. Ein Datum kann eine Routine verraten, auch wenn keine Straßenadresse vorhanden ist. Der Checker erklärt diese Hinweise anhand der gefundenen Felder. Höhere Punktzahlen bedeuten mehr erkannte Metadatenbedenken. Die Zahl ist keine Wahrscheinlichkeit einer Identifizierung und ersetzt nicht deine Entscheidung für den konkreten Empfänger.',
      'Beurteile einen Treffer nach seinem Inhalt, nicht nur nach seinem Feldnamen. Eine öffentliche Landmarke in einer gekennzeichneten Demonstration ist ein anderer Kontext als private Wohnungskoordinaten. Ein veralteter Name kann trotzdem unerwünscht sein. Die Werte lassen sich verändern oder kopieren; der Checker beweist deshalb weder einen Aufnahmeort noch eine Identität. Er macht lesbare Hinweise sichtbar, damit du eine passende öffentliche oder private Kopie wählen kannst.',
    ], fields: [
      { name: 'GPS-Koordinaten', meaning: 'Ein Gerät oder eine Anwendung kann einen genauen Ort speichern.', caveat: 'Koordinaten können geändert oder übernommen worden sein; sie belegen keinen realen Aufnahmeort.' },
      { name: 'Besitzer / Seriennummer', meaning: 'Kameraeinstellungen können dauerhafte Geräte- oder Namenshinweise hinterlassen.', caveat: 'Auch alte oder geerbte Labels verdienen vor öffentlicher Weitergabe eine Prüfung.' },
      { name: 'Kontakt / Autor', meaning: 'Bearbeitungsprogramme können Credits, Namen oder Kontaktdetails hinzufügen.', caveat: 'Eine Bildzusammenfassung zeigt nicht zwingend jede verwandte native Gruppe.' },
      { name: 'Datum / Software', meaning: 'Diese Angaben können Aufnahme, Bearbeitung oder Export beschreiben.', caveat: 'Gleich benannte Zeitfelder können unterschiedliche Ereignisse meinen.' },
    ] },
    { id: 'privacy-writers', title: 'Mehrere Programme können verschiedene Spuren ergänzen', paragraphs: [
      'Das Telefon kann GPS speichern, die Kamera ein Modell und der Editor einen Autor oder Softwarestand. Beim Export bleibt vielleicht nur ein Teil dieser Angaben erhalten. Ein niedriger Wert bei einer Kopie beschreibt deshalb nicht automatisch das Original. Prüfe die Datei, die du tatsächlich teilen möchtest. Bewahre ihre Herkunft und den Exportweg für deinen eigenen Vergleich, ohne diese Informationen unnötig an den Empfänger weiterzugeben.',
      'Ein Namensfeld ist nicht immer aktuell, und ein Datum muss kein Aufnahmedatum sein. Trotzdem können solche Records Rückschlüsse oder Verwechslungen auslösen. Suche bei einem auffälligen Treffer nach verwandten Werten in EXIF, XMP, IPTC und Textfeldern. Eine einzige entfernte Koordinate reicht nicht als vollständiger Vergleich, wenn andere lesbare Ortsangaben erhalten bleiben. Der Bericht erklärt, welche Felder gefunden wurden; er bewertet nicht sämtliche denkbaren Verknüpfungen außerhalb der Datei.',
    ] },
    { id: 'privacy-reading-limits', title: 'Ein niedriger Wert braucht eine abgeschlossene Prüfung', paragraphs: [
      'Lies die Scanabdeckung und Warnungen, bevor du dich auf die Punktzahl verlässt. Ein beschädigter oder nicht untersuchter Block bleibt eine Grenze. Keine erkannte Gefahr ist keine Garantie für ungeprüfte Bereiche. Warte auf den vollständigen Scan und suche native Felder, wenn eine Zusammenfassung leer wirkt. Eine fertige Suche ohne Treffer ist etwas anderes als eine Analyse, die wegen eines Fehlers keine verlässliche Antwort liefern konnte.',
      'Sichtbare Gesichter, Hausnummern, Kennzeichen, Bildschirmtexte und Spiegelungen liegen außerhalb dieses Metadatenscans. Auch der Dateiname kann private Informationen tragen. Nach einer Bereinigung musst du diese Hinweise selbst prüfen. Lies Restfelder und Verifikationswarnungen getrennt; ein niedriger Ausgangswert kann ein unvollständiges Ergebnis nicht aufheben. Je nach Empfänger kann eine andere Aufnahme, ein zugeschnittener Bildinhalt oder eine separate Inhaltsbearbeitung nötig sein, die dieser Checker nicht übernimmt.',
    ] },
    { id: 'privacy-controlled-example', title: 'Die Demonstration erklärt ein Feld, keine echte Person', paragraphs: [
      'Das Beispielbild enthält synthetische Kamerawerte, ViewExif Demo als Künstler und Koordinaten des öffentlichen Eiffelturm-Wahrzeichens. Das Bild selbst ist KI-generiert. Nutze es, um die Erklärung zu Orts- oder Namenshinweisen zu lesen. Es identifiziert keine echte Kameraaufnahme, keinen Fotografen und keine private Adresse. Das Bildschirmbild zeigt konkrete Demonstrationsfelder; seine Werte und mögliche Punktzahl sind keine Vorhersage für deine eigenen Bilder.',
      'Suche einen Beispielwert im vollständigen Bericht und notiere seinen Pfad. Wenn du die Datei bewusst bereinigst, lies anschließend das Ergebnis und öffne die erlaubte Ausgabe erneut. Ein anderer Hash zeigt eine Änderung, nicht vollständige Anonymität. Bewahre bei deiner eigenen Prüfung die Unterschiede zwischen entfernt, erhalten und verblieben. Die englische Anleitung erklärt ergänzend, wie du fehlende Werte von Lesefehlern unterscheidest, bevor du eine Freigabeentscheidung triffst.',
    ], figure: { src: '/editorial/image-sample.png', alt: 'Synthetische Bildfelder als Beispiel für Metadatenhinweise', caption: 'Demonstrationsmetadaten mit einem öffentlichen Ort. Ein lesbares Feld ist ein Hinweis und kein Beweis für ein tatsächliches Aufnahmeereignis.' } },
  ],
  remover: [
    { id: 'remover-field-table', title: 'Beschreibende Werte entfernen, notwendige Struktur erhalten', paragraphs: [
      'Ein Kameraname, Dokumentautor oder Audiokommentar ist etwas anderes als die Information, mit der ein Programm die Datei dekodiert. Der allgemeine Reiniger erkennt das Format und wählt die passende Strategie. Er ersetzt keine Inhaltsbearbeitung und verspricht keine leere Datei ohne irgendein technisches Feld. Vor dem Start suchst du die privaten Werte im Eingangsbericht. Danach prüfst du dieselben Quellen in der tatsächlichen Ausgabe und liest verbleibende Warnungen.',
      'Kameras, Office-Anwendungen, Recorder und Exportprogramme können die beschreibenden Werte schreiben. Ein späterer Editor kann sie in mehreren Gruppen kopieren. Ein sichtbarer Titel oder ein Dateiname allein zeigt deshalb nicht, wo ein Wert lebt. Die vollständigen Pfade helfen beim Vergleich. Auch wenn ein Programm ein Label nicht mehr anzeigt, kann ein anderer lesbarer Record es noch enthalten. Suche mehrere verwandte Bezeichnungen statt nur die erste Karte anzusehen.',
    ], fields: [
      { name: 'Bildlabels', meaning: 'Unterstützte beschreibende EXIF-, XMP-, IPTC- und Textwerte können Ziele sein.', caveat: 'Orientierung und Farbe können für die korrekte Darstellung erhalten bleiben.' },
      { name: 'Dokumenteigenschaften', meaning: 'PDF- und Office-Felder können Autor, Firma und eigene Werte tragen.', caveat: 'Text, Kommentare, Revisionen und Anhänge sind eine separate Inhaltsprüfung.' },
      { name: 'Audio- / Videotags', meaning: 'Container können Titel, Künstler, Datum, Ort und Software speichern.', caveat: 'Medieninhalt und nötige Spurenstruktur bleiben Teil der Ausgabe.' },
      { name: 'Removed / Preserved / Residual', meaning: 'Die Ausgabe unterscheidet entfernte, erhaltene und verbliebene Felder.', caveat: 'Die Zahl der Einträge ist kein Nachweis vollständiger Anonymität.' },
    ] },
    { id: 'remover-verification', title: 'Was bestätigt die erneute Analyse?', paragraphs: [
      'Nach der Bereinigung öffnet das Tool die neue Kopie wieder und prüft sie mit dem verfügbaren Parserumfang. Entfernt bedeutet, dass derselbe bereinigbare Eingangswert dort nicht mehr gefunden wurde. Erhalten benennt bewusst bewahrte Struktur oder Inhalte. Verblieben macht lesbare Werte sichtbar, die noch vorhanden sind oder neu auftauchen. Diese Unterschiede verhindern, dass ein notwendiger Codec wie eine private Notiz behandelt oder ein Restwert versteckt wird.',
      'Lies nicht nur die Anzahl. Prüfe die tatsächlichen Werte und die fehlgeschlagenen oder ausgelassenen Checks. Ein sauber aussehender Kurzbericht kann die Grenzen eines Parsers nicht aufheben. Die Prüfung deckt keine Gesichter, Sprache oder Namen im Dokumenttext ab. Ein neuer Hash ist nach Metadatenänderungen zu erwarten; er zeigt andere Bytes, nicht welche Eigenschaften verschwanden. Für eine Weitergabe zählt die untersuchte Ausgabe und nicht ein später umbenanntes Original.',
    ] },
    { id: 'remover-reading-limits', title: 'Bei blockierter oder unvollständiger Bereinigung stoppen', paragraphs: [
      'Ein geschütztes Dokument, beschädigter Container oder nicht unterstützter Record kann die Bereinigung begrenzen. Eine blockierte oder unvollständige Prüfung ist kein Erfolg. Bewahre das Original und lies die Diagnose. Eine geänderte Dateiendung macht das Format nicht kompatibel. Wenn du die Berechtigung hast, erzeuge eine unterstützte Sharing-Kopie in der ursprünglichen Anwendung und starte den Vergleich erneut. Es gibt keinen Grund, eine Warnung durch wiederholtes Klicken zu übergehen.',
      'Auch ein verifiziertes Ergebnis kann Restfelder enthalten. Entscheide anhand ihrer Werte, ob die Kopie für den Empfänger geeignet ist. Der Reiniger überschreibt das Original nicht und startet keinen Download durch normale Navigation. Prüfe eine erlaubte Ausgabe zusätzlich mit einem passenden Viewer und öffne oder spiele sie in deinem eigenen Programm ab. Verifikation der Struktur und inhaltliche Nutzbarkeit ergänzen sich; keine davon bescheinigt automatisch einen vollständig anonymen Inhalt.',
    ] },
    { id: 'remover-controlled-example', title: 'Mit einem markierten Wert einen vollständigen Vergleich üben', paragraphs: [
      'Die kontrollierte PNG-Datei misst 320 × 180 Pixel und trägt Author = Ada Example sowie Comment = Synthetic metadata cleanup sample. Ihr tatsächliches Ergebnis nennt 15 entfernte, 27 erhaltene und 29 verbliebene Felder. Die Verifikation meldet eine Ausgabe mit Restmetadaten und warnt vor den 29 verbleibenden Einträgen. Das ist keine Freigabe ohne Bedenken. Lies ihre konkreten Werte, statt eine kleinere Datei oder einen neuen Hash als vollständige Entfernung zu behandeln.',
      'Lade die erlaubte Kopie herunter und öffne genau diese Datei erneut. Vergleiche Format, Warnungen und Restwerte mit dem Eingang. Speichere bei Bedarf die Quittung als Protokoll des begrenzten Prüfumfangs, nicht als Beweis eines anonymen Dokuments. Kontrolliere zusätzlich den Dateinamen und den sichtbaren oder hörbaren Inhalt. Die englische Anleitung führt den Ablauf genauer durch und erklärt, warum kleinere Dateigröße oder ein anderer Hash allein keine Entfernung belegen.',
    ], figure: { src: '/editorial/cleanup-sample.png', alt: 'PNG-Bereinigung mit 15 entfernten, 27 erhaltenen und 29 verbliebenen Feldern', caption: 'Kontrolliertes Beispiel mit synthetischen Feldern, verifiziert mit Restmetadaten: 29 Felder bleiben. Lies Werte und Warnung vor der Entscheidung, diese bearbeitete Kopie zu teilen.' } },
  ],
  imageRemover: [
    { id: 'image-cleanup-field-table', title: 'Private Bildlabels und nötige Darstellungsfelder unterscheiden', paragraphs: [
      'Eine Kamera kann den Künstler, Besitzer oder Standort schreiben. Ein Editor kann dieselben Angaben später in XMP oder IPTC ergänzen. Suche vor der Bereinigung mehrere passende Begriffe und notiere die Feldfamilien. Der Bildreiniger bearbeitet unterstützte beschreibende Records, statt die Pixel absichtlich neu zu kodieren. Ein Bild darf danach weiterhin notwendige Angaben besitzen. Das Ziel ist eine geprüfte Sharing-Kopie und nicht ein kaputtes Format ohne lesbare Struktur.',
      'Besonders Orientierung und Farbprofil brauchen Aufmerksamkeit. Entfernst du blind alles, kann ein Bild gedreht erscheinen oder andere Farben zeigen. Der Reiniger erhält solche Angaben nach seiner Strategie. Ein technischer Rest ist deshalb nicht automatisch ein privat verbliebenes Besitzerlabel. Lies die Kategorien und konkreten Werte. Ein eigener Sichtvergleich der heruntergeladenen Kopie gehört außerdem dazu; der Metadatenbericht untersucht weder Gesichter noch Schrift oder andere Inhalte innerhalb der Pixel.',
    ], fields: [
      { name: 'EXIF / XMP / IPTC', meaning: 'Unterstützte beschreibende Felder können Kamera, Autor, Ort und Datum enthalten.', caveat: 'Prüfe alle Gruppen; eine leere Kamerakarte allein ist kein vollständiger Vergleich.' },
      { name: 'Kommentare / Text', meaning: 'Einzelne Bildformate speichern zusätzliche Notizen oder Softwarelabels.', caveat: 'Ein Wert kann außerhalb der vertrauten EXIF-Gruppe liegen.' },
      { name: 'Orientation / ICC', meaning: 'Ausrichtung und Farbinterpretation können absichtlich erhalten bleiben.', caveat: 'Ihre Funktion unterscheidet sich von einem privaten Namen oder einer Koordinate.' },
      { name: 'Animation / Abmessungen', meaning: 'Erforderliche Bildstruktur und animierte Inhalte sollen nutzbar bleiben.', caveat: 'Erhaltene Bildinhalte können weiterhin persönliche Hinweise zeigen.' },
    ] },
    { id: 'image-cleanup-writers', title: 'Ein Label kann in mehr als einer Familie stehen', paragraphs: [
      'Manche Arbeitsabläufe kopieren Credits und Datumswerte zwischen EXIF, XMP und IPTC. Andere schreiben nur eine Familie. Deshalb sagt ein fehlender erster Treffer wenig über verwandte Records aus. Suche den Wert selbst und mehrere passende Feldnamen. Bewahre seine native Quelle beim Vergleich. Ein späterer Export kann neue Software- oder Zeitlabels hinzufügen; prüfe immer die Kopie, die du tatsächlich an den Empfänger senden willst.',
      'Eine vollständige Ausgangsanalyse zeigt die heute lesbaren Angaben, nicht jede frühere Version des Bilds. Der Reiniger kann außerdem keine Einwilligung einer abgebildeten Person prüfen. Auch Kamera- und Künstlerlabels sind veränderbar. Beschreibe das Ergebnis deshalb als Entfernen unterstützter Metadaten mit erneuter Untersuchung. Es belegt weder eine echte Aufnahme noch anonymen Bildinhalt. Für Rechte, sichtbare Personen und den Veröffentlichungskontext brauchst du eine eigene Entscheidung.',
    ] },
    { id: 'image-cleanup-reading-limits', title: 'Eine Warnung nicht mit vollständiger Entfernung verwechseln', paragraphs: [
      'Warte auf die Analyse der Ausgabe. Fehlt ein Wert nach einer abgeschlossenen Prüfung, wurde der entsprechende bereinigbare Eingangswert dort nicht mehr gefunden. Ein beschädigter Block oder abgebrochener Parser begrenzt dagegen die Aussage. Eine unvollständige Bereinigung ist kein erfolgreiches Ergebnis. Bewahre das Original und lies den fehlgeschlagenen Check. Eine andere Dateiendung repariert weder Bildstruktur noch Metadaten, die der Parser nicht untersuchen konnte.',
      'Nach einer verifizierten Bereinigung schaust du getrennt auf erhaltene und verbliebene Felder. Ein notwendiges Farbprofil ist ein anderer Fall als eine verbleibende Ortsangabe. Nutze die tatsächlichen Werte, nicht nur Summen oder einen neuen Hash. Öffne die erlaubte Ausgabedatei in einem gewöhnlichen Bildprogramm und prüfe Ausrichtung, Farben und Animation. Diese Sichtkontrolle ergänzt den technischen Bericht, ersetzt aber nicht die Suche nach privaten Labels in den nativen Gruppen.',
    ] },
    { id: 'image-cleanup-example', title: 'Den Demonstrationskünstler vor und nach der Bereinigung suchen', paragraphs: [
      'Das Bereinigungsbeispiel nutzt eine erzeugte PNG-Datei mit 320 × 180 Pixeln, Author = Ada Example und Comment = Synthetic metadata cleanup sample. Die tatsächliche Ausgabe meldet 15 entfernte, 27 erhaltene und 29 verbliebene Felder. Die Warnung zu den Restmetadaten bleibt Teil des Ergebnisses. Diese Testwerte sind Lehrdaten, keine persönlichen Angaben. Suche die Eingangswerte samt Pfad und lies den Ausgabescan, ohne eine vollständig risikofreie Datei zu behaupten.',
      'Lade die erlaubte Ausgabe herunter und öffne sie erneut im Bildviewer. Suche denselben Wert und prüfe Restfelder samt Warnungen. Ein geänderter Hash ist normal, zeigt aber nur veränderte Bytes. Kontrolliere zusätzlich den Dateinamen sowie sichtbare Texte, Spiegelungen und Gesichter. Die englische Verifikationsanleitung erklärt diese getrennten Schritte. So kannst du einem Empfänger genau sagen, was geprüft wurde, ohne eine vollständige Anonymität zu versprechen.',
    ], figure: { src: '/editorial/cleanup-sample.png', alt: 'Kontrollierte PNG-Bereinigung mit 29 verbleibenden Feldern', caption: 'Das echte Beispiel nennt 15 entfernte, 27 erhaltene und 29 verbliebene Felder. Die Warnung verlangt Prüfung und bescheinigt kein risikofreies Bild.' } },
  ],
  videoRemover: [
    { id: 'video-cleanup-field-table', title: 'Private Containerlabels entfernen, Medienstruktur behalten', paragraphs: [
      'Ein Aufnahmeprogramm kann Ort, Datum oder Gerätelabels setzen. Ein Schnittprogramm kann später Titel, Encoder oder eigene Notizen ergänzen. Die Videobereinigung richtet sich nach dem echten Containerformat und bearbeitet unterstützte beschreibende Felder. Sie entfernt nicht die Bild- und Tonspuren oder kodiert sie absichtlich neu. Suche vorher die konkreten Werte im vollständigen Bericht. Ein Titel in einem Player kann aus einer anderen Quelle als dem zuerst gezeigten Label kommen.',
      'Zeitachsen, Spurreferenzen und Codecangaben bleiben nötig, damit ein Player das Video findet und dekodiert. Ihre Erhaltung ist ein anderer Sachverhalt als eine verbleibende private Ortsangabe. Lies deshalb die Kategorien und Werte im Ergebnis. Untertitel, Sprache, sichtbare Personen und Anlagen können ebenfalls erhalten bleiben. Wenn du einen öffentlichen Export brauchst, musst du diese Inhalte unabhängig von der Containerbereinigung betrachten; ein entfernter GPS-Tag macht die Szene nicht anonym.',
    ], fields: [
      { name: 'Titel / Kommentar / Ort', meaning: 'Unterstützte beschreibende Containerrecords können bereinigt werden.', caveat: 'Nicht jede zeitbezogene Telemetrie ist ein einzelner gewöhnlicher Ortsstring.' },
      { name: 'Datum / Software', meaning: 'Recorder und Editoren können Aufnahme- oder Exportlabels schreiben.', caveat: 'Ein Datum kann eine spätere Verarbeitung statt das Filmen beschreiben.' },
      { name: 'Codec / Spurreferenzen', meaning: 'Der Container braucht technische Angaben zur Wiedergabe.', caveat: 'Erhaltene Struktur ist nicht dasselbe wie ein verbliebener privater Kommentar.' },
      { name: 'Untertitel / Anhänge', meaning: 'Die Strategie erhält Medien- und unterstützte Zusatzinhalte.', caveat: 'Namen oder Orte in diesen Inhalten brauchen eine eigene Prüfung.' },
    ] },
    { id: 'video-cleanup-writers', title: 'Die tatsächlich versendete Kopie vergleichen', paragraphs: [
      'Nach der Kamera können mehrere Editoren und Exportprogramme beteiligt sein. Einer kopiert Tags, ein anderer schreibt neue Datums- oder Softwarelabels. Vergleiche deshalb nicht nur die ursprüngliche Aufnahme mit irgendeiner Vorschau. Prüfe die Ausgabe, die du tatsächlich versenden möchtest, und halte ihren Exportweg fest. Ein Player kann den Dateinamen als Titel anzeigen; das beweist keine verbliebene eingebettete Titelangabe. Die Feldsuche trennt diese Beobachtungen.',
      'Ein lesbarer Ort kann geändert oder aus einem älteren Projekt kopiert sein. Ein Encoderlabel kann nur die letzte Verarbeitungsstation zeigen. Solche Angaben verdienen eine Privatsphäreprüfung, aber sie erzählen keine sichere Aufnahmegeschichte. Suche Werte und passende Gruppen vor und nach dem Reinigen. Der Bericht darf verbleibende beschreibende Felder nicht als entfernt ausgeben, nur weil ein technischer Strukturcheck erfolgreich war oder die Ausgabedatei etwas kleiner geworden ist.',
    ] },
    { id: 'video-cleanup-reading-limits', title: 'Unvollständige Verifikation ist kein sauberer Export', paragraphs: [
      'Eine beschädigte Indexstruktur, ein nicht unterstützter Containerteil oder ein Parserabbruch kann die Prüfung begrenzen. Warte auf den Abschluss und lies den Status. Eine blockierte oder unvollständige Bereinigung ist kein Erfolg. Bewahre das Original und die Diagnose. Eine neue Dateiendung löst das Problem nicht. Wenn du eine Alternative erzeugen darfst, exportiere eine unterstützte Kopie in deiner Anwendung und prüfe diese mit dokumentierten Einstellungen erneut.',
      'Bei einer erlaubten Ausgabe prüfst du entfernt, erhalten und verblieben einzeln. Schau nach dem eigentlichen Orts- oder Kommentarin­halt, nicht nur nach der Anzahl. Öffne das heruntergeladene Video in deinem eigenen Player und kontrolliere seine Nutzbarkeit. Ein neuer Hash zeigt geänderte Bytes, keine vollständige Entfernung sämtlicher denkbarer versteckter Records. Die hörbare Sprache und sichtbaren Bilder gehören weiterhin zu einer getrennten Inhaltsprüfung vor der Veröffentlichung.',
    ] },
    { id: 'video-cleanup-example', title: 'Ein Testlabel durch den Ablauf verfolgen', paragraphs: [
      'Das gezeigte MP4-Beispiel enthält nur einen Container mit Zeitskala 1000 und Dauer 1000 Einheiten. Es besitzt keine tatsächlichen Medienspuren und lässt sich nicht als Video abspielen. Der Bericht erklärt damit die Grenzen einer Headeranalyse, nicht eine erfolgreich bereinigte Aufnahme. Bewahre diese Einschränkung bei jedem Vergleich. Die Beispielwerte behaupten keinen realen Filmtermin und keine allgemeine Unterstützung aller Telemetriearten oder Kameraexporte durch den Reiniger.',
      'Bei einer eigenen abspielbaren Aufnahme notierst du zuerst die tatsächlichen beschreibenden Werte und Spuren. Starte die Bereinigung bewusst, warte auf Verifikation und untersuche die erlaubte heruntergeladene Kopie erneut. Erst für solche Medien ist ein zusätzlicher Abspieltest sinnvoll. Die englische Anleitung trennt Tagentfernung, Struktur und Nutzbarkeit. Übertrage den Ablauf auf deine Datei, nicht ein erfundenes Erfolgsergebnis oder eine Medienprüfung, die der spurfreie Demonstrationscontainer überhaupt nicht ermöglichen kann.',
    ], figure: { src: '/editorial/video-sample.png', alt: 'Synthetischer MP4-Container ohne tatsächliche Medienspuren', caption: 'Eine reine Container-Lesedemonstration. Sie ist kein abspielbares Video und kein Beleg erfolgreicher Videobereinigung.' } },
  ],
  audioRemover: [
    { id: 'audio-cleanup-table', title: 'Welche Audiolabels sind Bereinigungsziele?', paragraphs: [
      'Ein Recorder schreibt vielleicht Datum und Software, ein Tag-Editor später Interpret, Album und Kommentar. Der Audioreiniger bearbeitet unterstützte beschreibende Records und nimmt den Klang nicht erneut auf. Bevor du startest, suche die unerwünschten Labels im vollständigen Bericht und notiere ihre Familie. Ein Titel allein zeigt nicht, ob ID3, Vorbis, ASF oder eine andere Struktur den Wert trägt. Die echte Dateisignatur bestimmt den passenden Weg.',
      'Ein Player kann einen Titel aus dem Dateinamen oder aus einer Bibliothek anzeigen. Das ist nicht automatisch ein Dateitag. Manche Dateien besitzen mehrere lesbare Quellen für ähnliche Labels. Für einen sinnvollen Vergleich brauchst du deshalb Werte und Pfade, nicht nur die erste Zusammenfassung. Eine Privatsphärebereinigung ist außerdem etwas anderes als eine Musikbibliothek ohne jedes Cover, jedes Kapitel und jeden Credit aufzubauen. Die erhaltenen Inhalte bleiben ausdrücklich Teil der Ausgabe.',
    ], fields: [
      { name: 'ID3 Titel / Interpret', meaning: 'MP3-Frames können Namen, Notizen, Datumswerte und Links enthalten.', caveat: 'Ein Player zeigt möglicherweise nur eine bevorzugte Tagversion.' },
      { name: 'Vorbis / ASF / RIFF', meaning: 'Andere Container besitzen eigene beschreibende Recordstrukturen.', caveat: 'Eine geänderte Dateiendung ändert weder Struktur noch Bereinigungsengine.' },
      { name: 'Bilder / Kapitel', meaning: 'Die Strategie erhält unterstütztes Artwork und Kapitelinhalte.', caveat: 'Cover oder Kapitelnamen können weiterhin Personen oder Projekte erkennen lassen.' },
      { name: 'Dauer / Kanäle / Abtastrate', meaning: 'Technische Streamdaten bleiben erhalten und werden geprüft.', caveat: 'Gleiche Header allein beweisen nicht, dass alle beschreibenden Felder verschwanden.' },
    ] },
    { id: 'audio-cleanup-residuals', title: 'Warum erhaltene und verbliebene Werte getrennt stehen', paragraphs: [
      'Nötige Audioheader sollen bleiben. Artwork und Kapitel bleiben ebenfalls unter der Metadatenstrategie. Ein beschreibender Kommentar, den der Ausgabescan noch findet, ist dagegen ein Restwert und braucht eine Erklärung. Lies seinen Inhalt und entscheide für den Empfänger. Die Zahl der entfernten Tags sagt wenig aus, wenn eine unerwünschte Notiz erhalten ist. Umgekehrt ist ein behaltenes technisches Feld nicht automatisch ein Fehler oder ein privater Hinweis.',
      'Eine Aufnahme kann auch ohne Texttags Namen, Gespräche oder Orte verraten. Das Tool hört nicht zu und transkribiert nichts. Ein sauberer Eigenschaftenbericht bescheinigt deshalb keinen anonymen Ton. Prüfe hörbaren Inhalt, Dateiname und erhaltene Bilder selbst. Wenn du eine Quittung speicherst, behandle sie als Protokoll begrenzter Prüfungen. Sie belegt nicht Urheberschaft, Einwilligung oder die Abwesenheit jedes persönlichen Hinweises im Medium oder außerhalb davon.',
    ] },
    { id: 'audio-cleanup-reading-limits', title: 'Eine beschädigte Tagstruktur nicht als Erfolg ausgeben', paragraphs: [
      'Warte auf Bereinigung und erneute Analyse. Ein beschädigter Tagblock oder nicht unterstützter Containerteil kann die Prüfung begrenzen. Eine unvollständige oder blockierte Bereinigung ist kein Erfolg, auch wenn ein Kurzpanel leer aussieht. Bewahre das Original und lies den fehlgeschlagenen Check. Ein anderer Dateiname repariert keine beschädigte Datei. Nutze bei vorhandener Berechtigung einen unterstützten Export und dokumentiere, welche Anwendung und Einstellungen diese Kopie erzeugten.',
      'Wenn eine Ausgabe erlaubt wird, suche die ursprünglichen Labels erneut im Audioviewer. Vergleiche technische Header getrennt und spiele die Datei in deinem eigenen Player ab. Ein neuer Hash ist nach Änderungen normal, zeigt aber nur andere Bytes. Er sagt nicht, welcher Kommentar verschwand oder ob jede Struktur lesbar war. Lies verbliebene Werte und Warnungen, bevor du diese Kopie sendest, statt nur die grüne Schlusszeile oder eine Dateigröße zu betrachten.',
    ] },
    { id: 'audio-cleanup-example', title: 'Einen Demonstrationstag als festes Suchziel wählen', paragraphs: [
      'Der WAV-Eingang heißt Synthetic silence und trägt Artist = Ada Example. Gemeldet werden Mono-PCM, 8 kHz, 16 Bit und 1,00 Sekunde Dauer. Eine Warnung zur Datenblockgröße bleibt sichtbar und darf durch zusätzliche lesbare Felder nicht ausgeblendet werden. Das Bildschirmbild zeigt die synthetische Eingangsdatei, nicht eine erfolgreiche Audiobereinigung. Die markierten Tags behaupten weder einen realen Musiker noch eine Studiositzung. Bewahre den Tagpfad samt Warnung für einen späteren tatsächlichen Vergleich.',
      'Öffne die heruntergeladene Ausgabe erneut und suche das gewählte Label in derselben Gruppe. Kontrolliere erhaltenes Artwork sowie die hörbare Nutzbarkeit. Ein erfolgreicher Labelvergleich beantwortet eine konkrete Frage, nicht jede mögliche Privatsphärefrage. Übertrage den Ablauf auf deine eigenen Dateien und lies ihren individuellen Restbericht. Die englische Anleitung erklärt zusätzlich, wie entfernt, erhalten und verblieben mit Hashes und Strukturprüfungen zusammenhängen, ohne daraus eine pauschale Anonymitätsbescheinigung zu machen.',
    ], figure: { src: '/editorial/audio-sample.png', alt: 'Kontrollierter Audioeingang mit markierten Beispieltags', caption: 'Eine synthetische Aufnahme liefert ein nachvollziehbares Suchziel. Bereinigung und hörbare Inhaltsprüfung sind getrennte Aufgaben.' } },
  ],
  documentRemover: [
    { id: 'document-cleanup-scope', title: 'Eigenschaften bereinigen ist keine Schwärzung des Dokuments', paragraphs: [
      'Eine Word-Vorlage kann einen früheren Autor oder Firmennamen mitbringen. Ein PDF-Exporter kann diese Angaben übernehmen und eigene Softwarelabels ergänzen. Der Dokumentreiniger bearbeitet unterstützte PDF- und Office-Eigenschaften. Er entfernt keine Namen im Text, Kommentare, Überarbeitungen, Formulare oder Anhänge. Entscheide vor der öffentlichen Weitergabe, ob du Eigenschaften, Inhalte oder beides bearbeiten musst. Eine leere Autorenkarte beantwortet nur einen kleinen Teil dieser Aufgabe.',
      'Suche die unerwünschten Werte zuerst in allen lesbaren Gruppen und bewahre ihre Pfade für den Vergleich. Ein PDF kann Info und XMP gleichzeitig besitzen. Ein Office-Paket kann eigene Projekteigenschaften neben vertrauten Standardfeldern enthalten. Ein späterer Export kann neue Erstellerlabels ergänzen. Prüfe deshalb die tatsächlich versendete Kopie. Der Dateiname und der sichtbare Titel ersetzen keine Suche nach intern gespeicherten Autoren- oder Firmenangaben.',
    ], fields: [
      { name: 'PDF Info / oberstes XMP', meaning: 'Die PDF-Strategie lässt diese beschreibenden Records beim Neuschreiben weg.', caveat: 'Verschachtelte Records und Anmerkungen erfordern Restbericht und Inhaltsprüfung.' },
      { name: 'Office Core / App / Custom', meaning: 'Eigenschaftsteile können Autor, Firma, Datum und eigene Werte tragen.', caveat: 'Eine Änderung ersetzt keine Namen in Zellen, Folien, Text oder Revisionen.' },
      { name: 'Seiten / Paketstruktur', meaning: 'Nötige Records erhalten die Nutzbarkeit der Ausgabedatei.', caveat: 'Erhaltene Struktur bescheinigt keine Abwesenheit persönlicher Inhalte.' },
      { name: 'Digitale Signaturen', meaning: 'Eine Änderung der Datei kann eine an Originalbytes gebundene Signatur betreffen.', caveat: 'Bewahre das signierte Original und lies die Warnung vor einer Sharing-Kopie.' },
    ] },
    { id: 'document-cleanup-writers', title: 'Alte Profilwerte und mehrere Autorquellen erkennen', paragraphs: [
      'Office kann Namen aus einem Benutzerprofil setzen. Eine Vorlage kann weitere Werte übernehmen, die ein neuer Bearbeiter nie bewusst eingegeben hat. Ein PDF-Export kann solche Angaben in Info und XMP weitertragen. Ein Firmenfeld kann alt sein, obwohl das Dokument einen aktuellen Titel zeigt. Ein Treffer ist deshalb ein Privatsphärehinweis, aber kein sicherer Beweis dafür, wer den Text verfasst oder die letzte Änderung vorgenommen hat.',
      'Halte die Eingangs- und Ausgabekopie klar auseinander. Ein neues lokales Dateidatum kann vom Herunterladen stammen, während interne Werte etwas anderes zeigen. Ein neuer Hash ist nach dem Neuschreiben normal, sagt jedoch nicht, welche Namen verschwanden. Für eine nachvollziehbare Prüfung brauchst du die ursprünglichen Felder, die tatsächlich heruntergeladene Ausgabe und den Restbericht. Ein anderer sichtbarer Titel oder eine kleinere Datei ersetzt diesen Vergleich nicht.',
    ] },
    { id: 'document-cleanup-reading-limits', title: 'Geschützte und beschädigte Dateien ehrlich behandeln', paragraphs: [
      'Ein geschütztes PDF oder beschädigtes Office-Paket ist keine erfolgreiche Bereinigung. ViewExif knackt keine Passwörter. Alte Office-Dateien werden durch Umbenennen nicht zu unterstützten neuen Paketen. Bewahre das Original und lies Fehler sowie Prüfdaten. Wenn du die Berechtigung besitzt, erzeuge eine unterstützte Weitergabekopie in der passenden Anwendung. Eine leere Zusammenfassung bei einem Parserfehler darf nicht als Nachweis vollständiger Entfernung persönlicher Eigenschaften gelten.',
      'Nach einer abgeschlossenen Bereinigung liest du entfernte, erhaltene und verbliebene Werte einzeln. Suche die alten Namen in den ursprünglichen Gruppen. Öffne die Ausgabe zusätzlich in einem normalen Leser und prüfe Seitenbild, Kommentare und Anlagen. Bei signierten Dokumenten bleibt das Original besonders wichtig: Eine neue Kopie darf nicht mit unveränderter ursprünglicher Signatur beschrieben werden. Der Eigenschaftenreiniger übernimmt weder eine rechtliche Beweisbewertung noch eine vollständige Schwärzung sichtbarer oder eingebetteter Inhalte.',
    ] },
    { id: 'document-cleanup-example', title: 'Eine markierte Eigenschaft vor und nach dem Reinigen suchen', paragraphs: [
      'Das kontrollierte DOCX-Beispiel trägt Synthetic review copy als Titel, Ada Example als Autor, Example Studio als Firma und Review status = Draft als eigene Eigenschaft. Suche die Werte in ihren Kern-, Anwendungs- und eigenen Gruppen. Das Bildschirmbild zeigt den synthetischen Eingang, keine erfolgreiche Bereinigung. Bei einem bewusst gestarteten Vergleich musst du die tatsächliche Ausgabe und ihre Verifikation lesen. Eine markierte Testdatei verspricht keine identischen Eigenschaften jedes Dokumentprogramms.',
      'Lade die erlaubte Ausgabe herunter und öffne genau diese Datei erneut. Bewahre bei Bedarf die Quittung als Protokoll der verfügbaren Checks. Prüfe den sichtbaren Inhalt, den Dateinamen und Anlagen unabhängig davon. So bleibt klar, welche Eigenschaft nicht mehr gefunden wurde und welche Prüfung offen blieb. Die englische Verifikationsanleitung erklärt diesen Ablauf genauer. Ein geänderter Hash oder eine erfolgreiche Strukturprüfung allein macht ein Dokument weder anonym noch wieder zu seinem signierten Original.',
    ], figure: { src: '/editorial/document-sample.png', alt: 'Synthetische DOCX-Eigenschaften als Vergleichsziele', caption: 'Ein kontrollierter Office-Eingangsbericht. Untersuche eine tatsächlich erzeugte Ausgabe und ihren sichtbaren Inhalt getrennt.' } },
  ],
  c2pa: [
    { id: 'c2pa-state-table', title: 'Jeden Verifikationsstatus als eigene Prüfung lesen', paragraphs: [
      'Eine Content Credential enthält signierte Aussagen zu einer Datei. Die erzeugende oder signierende Anwendung schreibt sie. Ein gewöhnliches Kameralabel wird dadurch nicht automatisch zur Signatur. ViewExif trennt lesbare Herkunft, Bindungsprüfungen und Grenzen lokaler Verifikation. Lies den konkreten Status und seine Details. Ein pauschales Urteil wie echt oder gefälscht würde mehr behaupten, als eine einzelne Prüfung von Dateibytes oder einer signierten Aussage belegen kann.',
      'Die Bedeutung hängt auch davon ab, welcher Schritt abgeschlossen wurde. Ein gefundenes Manifest, eine gültige Bindung und eine extern geprüfte Vertrauenswürdigkeit des Signierers sind verschiedene Dinge. Dieser lokale Reader fragt keine externe Trust List oder Sperrstelle ab. Solche Prüfungen können deshalb offen bleiben. Auch eine gültige Signatur beweist nicht, dass jedes Bilddetail, jeder Ton oder jede inhaltliche Aussage im Manifest tatsächlich wahr ist.',
    ], fields: [
      { name: 'Keine lesbare Credential', meaning: 'Der lokale Reader hat keine eingebettete auswertbare Credential erhalten.', caveat: 'Nie signiert, beim Export verloren und nicht unterstützte Struktur sind verschiedene Möglichkeiten.' },
      { name: 'Bindung / Signatur', meaning: 'Ein gemeldeter Check betrifft die Aussage oder ihre Verbindung zu diesen Bytes.', caveat: 'Eine fehlgeschlagene Prüfung benennt nicht automatisch Verursacher oder Absicht einer Änderung.' },
      { name: 'Trust / Widerruf offen', meaning: 'Externe Listen und Zertifikats-Sperrstellen werden hier nicht abgefragt.', caveat: 'Ein lokaler Status darf keine abgeschlossene externe Vertrauensprüfung vortäuschen.' },
      { name: 'Assertions / Ingredients', meaning: 'Ein Manifest kann Aktionen, Programme und Ausgangsmaterialien beschreiben.', caveat: 'Eine signierte Aussage ist kein unabhängiger Wahrheitsbeweis für die dargestellte Szene.' },
    ] },
    { id: 'c2pa-writers', title: 'Eine Herkunftsangabe hat andere Grenzen als EXIF', paragraphs: [
      'Eine Kamera, ein Editor oder eine andere signierende Anwendung kann ein Manifest erzeugen und darin Bearbeitungsschritte erklären. Normale EXIF- oder XMP-Texte sind dagegen gewöhnlich frei veränderbare Beschreibungen. Ein Künstlername kann sinnvoll sein, aber er authentifiziert keine Person. Vergleiche diese Arten von Information nicht wie austauschbare Labels. Der C2PA-Bericht dient dem Lesen und Prüfen vorhandener eingebetteter Provenienz, nicht der nachträglichen Ermittlung jeder Bearbeitungsstation.',
      'Ein Export kann die Credential verlieren oder eine neue erzeugen. Die heute ausgewählte Kopie ist deshalb entscheidend. Ein Remote-Manifest, das nur anderswo verknüpft ist, wird von dieser lokalen Seite nicht abgerufen. Bewahre das Original, wenn du eine Veränderung untersuchst. Notiere bekannte Exportoptionen und die tatsächlich gemeldeten Zustände. Ein fehlender Datensatz allein identifiziert weder KI-Inhalt noch eine Fälschung oder einen bewusst entfernten Herkunftsnachweis.',
    ] },
    { id: 'c2pa-reading-limits', title: 'Fehlend, nicht lesbar und ungültig auseinanderhalten', paragraphs: [
      'Beginne mit dem erkannten Format und dem Readerstatus. Eine nicht unterstützte Struktur oder ein Parserfehler begrenzt die Untersuchung. Das ist etwas anderes als eine abgeschlossene Suche ohne eingebettete Credential. Lies die Diagnose im Detailbereich, ohne einen technischen Fehler als moralisches Urteil über die Datei zu übersetzen. Viele echte Dateien wurden nie signiert. Andere verloren Herkunftsdaten beim Export. Diese Möglichkeiten bleiben ohne weitere Belege offen.',
      'Verändere das signierte Beispiel nicht durch Skalieren, Transkodieren oder Metadatenneuschreiben, nur um es leichter auszuwählen. Geschützte Bytes und Credentialrecords nehmen an der Prüfung teil. Ein danach gemeldeter Fehler würde die geänderte Kopie betreffen. Für einen Vergleich brauchst du klar beschriftete Dateien und dokumentierte Transformationen. Nenne nur die Prüfungen, die der tatsächliche Verifier meldet, und behaupte kein bestimmtes Fehlerbild, bevor du diesen Zustand beobachtet hast.',
    ] },
    { id: 'c2pa-controlled-example', title: 'Ein signiertes Testbild und ein unsigniertes Demo unterscheiden', paragraphs: [
      'Das Bildschirmbild verwendet ein unsigniertes Demonstrations-JPEG und zeigt das lokale Ergebnis ohne lesbare Credential. Es zeigt keinen Signaturfehler und keine KI-Klassifikation. Das gewöhnliche ViewExif-Metadatenbild ist KI-generiert und trägt absichtlich gesetzte Kamerafelder. Diese Labels machen daraus keine echte Kameraaufnahme oder signierte Datei. Lies zuerst Erklärung und nächsten Schritt. Die technischen Details können den Zustand erläutern, aber keinen nicht vorgenommenen Signaturcheck nachträglich bestätigen.',
      'Als getrenntes signiertes Beispiel steht das dokumentierte Adobe-Testbild aus dem öffentlichen C2PA-Testdateirepository bereit. Seine Bytes bleiben unverändert. Öffne es und lies sein tatsächliches Manifest und die Zustände, statt sein Ergebnis mit dem unsignierten Bildschirmbild gleichzusetzen. Fehlende Credentials sind kein KI-Detektor und EXIF-Namen keine authentifizierten Identitäten. Die englische Anleitung erklärt die Gruppen genauer. Auch eine gültige Bindung beweist weder jede Aussage noch eine externe Vertrauenswürdigkeit des Signierers.',
    ], figure: { src: '/editorial/c2pa-sample.png', alt: 'Lokales Ergebnis ohne Credential für ein unsigniertes Demonstrations-JPEG', caption: 'Ein unsigniertes Beispiel ohne lesbare Credential. Das ist kein fehlgeschlagener Signaturcheck und kein Urteil über die Echtheit des Bilds.' } },
  ],
};
